//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.Common.Util.Web.Captcha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaptchaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptchaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.Common.Util.Web.Captcha.CaptchaResources", typeof(CaptchaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نمایش داده شده در تصویر درست نیست. مجدداً امتحان کنید، و دقت کنید که پس از نمایش تصویر مدت زمان محدودی برای وارد کردن آن فرصت دارید..
        /// </summary>
        internal static string ImageCaptchaNotAcceptable {
            get {
                return ResourceManager.GetString("ImageCaptchaNotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرورگر شما از جاوا اسکریپت پشتیبانی نمی کند، یا در تنظیمات آن جاوا اسکریپت را خاموش کرده اید؛ چرا که مکانیزم تشخیص ربات سایت به درستی کار نمی کند. لطفاً برای استفاده از سایت از مرورگرهای مدرن استفاده کنید و از فعال بودن جاوا اسکریپت اطمینان حاصل کنید. برای کسب اطلاعات بیشتر در مورد نحوه تشخیص ربات ها، امنیت در سایت و مرورگرهای پشتیبانی شده به راهنما مراجعه کنید..
        /// </summary>
        internal static string ScriptCaptchaNotAcceptable {
            get {
                return ResourceManager.GetString("ScriptCaptchaNotAcceptable", resourceCulture);
            }
        }
    }
}
