//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Controllers.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublishValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublishValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Controllers.Property.PublishValidationErrors", typeof(PublishValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد تحویل ملک (به صورت تاریخ مشخص) وارد نشده است..
        /// </summary>
        public static string AbsoluteDeliveryDate_ValueNotSpecified {
            get {
                return ResourceManager.GetString("AbsoluteDeliveryDate_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل واحد های ساختمان مشخص نشده است..
        /// </summary>
        public static string Building_TotalNumberOfUnits_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Building_TotalNumberOfUnits_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات ساختمان خالی است..
        /// </summary>
        public static string BuildingIsNull {
            get {
                return ResourceManager.GetString("BuildingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه ارائه اطلاعات بنگاه معاملات ملکی انتخاب شده، ولی نام بنگاه مشخص نشده است..
        /// </summary>
        public static string ContactInfo_AgencyName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_AgencyName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص در قسمت اطلاعات تماس مشخص نشده است..
        /// </summary>
        public static string ContactInfo_ContactName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_ContactName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن در قسمت اطلاعات تماس ارائه نشده است..
        /// </summary>
        public static string ContactInfo_ContactPhone1_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_ContactPhone1_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در اطلاعات تماس، گزینه مالک / بنگاه معاملات ملکی انتخاب نشده است..
        /// </summary>
        public static string ContactInfo_ContactRole_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_ContactRole_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد تحویل مشخص نشده است..
        /// </summary>
        public static string ContactInfo_DeliveryDateSpecificationType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_DeliveryDateSpecificationType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با وجود مشخص کردن امکان تماس مستقیم با مالک، نام مالک وارد نشده است..
        /// </summary>
        public static string ContactInfo_OwnerName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_OwnerName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با وجود مشخص کردن امکان تماس مستقیم با مالک، تلفن مالک وارد نشده است..
        /// </summary>
        public static string ContactInfo_OwnerPhone1_ValueNotSpecified {
            get {
                return ResourceManager.GetString("ContactInfo_OwnerPhone1_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس انتخاب شده غیر مجاز است.
        /// </summary>
        public static string ContactInfo_RelatedEntityIsNotPermitted {
            get {
                return ResourceManager.GetString("ContactInfo_RelatedEntityIsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس خالی است..
        /// </summary>
        public static string ContactInfoIsNull {
            get {
                return ResourceManager.GetString("ContactInfoIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد تحویل ملک مشخص نشده است..
        /// </summary>
        public static string DeliveryDateSpecificationType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("DeliveryDateSpecificationType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد تحویل ملک (به صورت تعداد روز بعد از قرارداد) مشخص نشده است..
        /// </summary>
        public static string DeliveryDaysAfterContract_ValueNotSpecified {
            get {
                return ResourceManager.GetString("DeliveryDaysAfterContract_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت زمین مشخص نشده است..
        /// </summary>
        public static string Estate_Area_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_Area_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهری که ملک در آن واقع است مشخص نشده است..
        /// </summary>
        public static string Estate_City_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_City_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه شهرداری که ملک در آن واقع است مشخص نشده است..
        /// </summary>
        public static string Estate_CityRegion_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_CityRegion_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در قسمت مشخصات زمین، جهت زمین مشخص نشده است..
        /// </summary>
        public static string Estate_Direction_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_Direction_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله ای که ملک در آن واقع است مشخص نشده است..
        /// </summary>
        public static string Estate_Neighborhood_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_Neighborhood_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استانی که ملک در آن واقع شده است مشخص نشده است..
        /// </summary>
        public static string Estate_Province_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_Province_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشش زمین مشخص نشده است..
        /// </summary>
        public static string Estate_SurfaceType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_SurfaceType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً موقعیت جغرافیایی را دقیق تر مشخص کنید..
        /// </summary>
        public static string Estate_Vicinity_SelectedVicinityCannotContainPropertyRecords {
            get {
                return ResourceManager.GetString("Estate_Vicinity_SelectedVicinityCannotContainPropertyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محلی که ملک در آن واقع است مشخص نشده است..
        /// </summary>
        public static string Estate_Vicinity_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_Vicinity_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت جغرافیایی مشخص شده، فعلاً غیرفعال است..
        /// </summary>
        public static string Estate_Vicinity_ValueTargetIsDisabled {
            get {
                return ResourceManager.GetString("Estate_Vicinity_ValueTargetIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در قسمت مشخصات زمین، نوع سند آن مشخص نشده است..
        /// </summary>
        public static string Estate_VoucherType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Estate_VoucherType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات زمین خالی است..
        /// </summary>
        public static string EstateIsNull {
            get {
                return ResourceManager.GetString("EstateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که پیش از بازدید نیاز به هماهنگی می باشد، لطفاً نحوه هماهنگی را مشخص نمایید..
        /// </summary>
        public static string HowToCoordinateBeforeVisit_ValueNotSpecified {
            get {
                return ResourceManager.GetString("HowToCoordinateBeforeVisit_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت قابلیت انعطاف در تبدیل اجاره  / ودیعه، حداقل مبلغ اجاره یا قرض الحسنه باید مشخص شود..
        /// </summary>
        public static string RentConditions_MinimumRent_ValueNotSpecified {
            get {
                return ResourceManager.GetString("RentConditions_MinimumRent_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ودیعه درخواستی جهت قرارداد اجاره مشخص نشده است..
        /// </summary>
        public static string RentConditions_Mortgage_ValueNotSpecified {
            get {
                return ResourceManager.GetString("RentConditions_Mortgage_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ اجاره درخواستی مشخص نشده است..
        /// </summary>
        public static string RentConditions_Rent_ValueNotSpecified {
            get {
                return ResourceManager.GetString("RentConditions_Rent_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط اجاره خالی است..
        /// </summary>
        public static string RentConditionsIsNull {
            get {
                return ResourceManager.GetString("RentConditionsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تقسیط در پرداخت مشخص شده، اما نوع تضمین مورد نیاز ذکر نشده است..
        /// </summary>
        public static string SaleConditions_DebtGuaranteeType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_DebtGuaranteeType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تقسیط در پرداخت مشخص شده، اما حداکثر مبلغ قابل تقسیط ذکر نشده است..
        /// </summary>
        public static string SaleConditions_PaymentPercentForDebt_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_PaymentPercentForDebt_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی جهت فروش ملک مشخص نشده است..
        /// </summary>
        public static string SaleConditions_Price_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_Price_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی جهت فروش ملک مشخص نشده است..
        /// </summary>
        public static string SaleConditions_PricePerEstateArea_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_PricePerEstateArea_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی جهت فروش ملک مشخص نشده است..
        /// </summary>
        public static string SaleConditions_PricePerUnitArea_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_PricePerUnitArea_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی جهت فروش ملک مشخص نشده است..
        /// </summary>
        public static string SaleConditions_PriceSpecificationType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_PriceSpecificationType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک دارای وام قابل انتقال است، ولی مبلغ باقی مانده از وام ذکر نشده است..
        /// </summary>
        public static string SaleConditions_TransferableLoanAmountM_ValueNotSpecified {
            get {
                return ResourceManager.GetString("SaleConditions_TransferableLoanAmountM_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط فروش خالی است..
        /// </summary>
        public static string SaleConditionsIsNull {
            get {
                return ResourceManager.GetString("SaleConditionsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت واحد مشخص نشده است..
        /// </summary>
        public static string Unit_Area_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Unit_Area_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق های واحد مشخص نشده است..
        /// </summary>
        public static string Unit_NumberOfRooms_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Unit_NumberOfRooms_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربری در مشخصات واحد انتخاب نشده است..
        /// </summary>
        public static string Unit_UsageType_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Unit_UsageType_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات واحد خالی است..
        /// </summary>
        public static string UnitIsNull {
            get {
                return ResourceManager.GetString("UnitIsNull", resourceCulture);
            }
        }
    }
}
