//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyRentPaymentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyRentPaymentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Property.PropertyRentPaymentResources", typeof(PropertyRentPaymentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت پرداخت اجاره به صورت یکجا، تخفیف داده می شود.
        /// </summary>
        public static string Label_DiscountOnBulkPayment {
            get {
                return ResourceManager.GetString("Label_DiscountOnBulkPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه چک تضمین تخلیه الزامی است.
        /// </summary>
        public static string Label_IsDischargeGuaranteeChequeRequired {
            get {
                return ResourceManager.GetString("Label_IsDischargeGuaranteeChequeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر مدت زمان قرارداد.
        /// </summary>
        public static string Label_MaximumContractDuration {
            get {
                return ResourceManager.GetString("Label_MaximumContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مدت زمان قرارداد.
        /// </summary>
        public static string Label_MinimumContractDuration {
            get {
                return ResourceManager.GetString("Label_MinimumContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ ودیعه.
        /// </summary>
        public static string Label_MinimumMortgage {
            get {
                return ResourceManager.GetString("Label_MinimumMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل اجاره ماهانه.
        /// </summary>
        public static string Label_MinimumRent {
            get {
                return ResourceManager.GetString("Label_MinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ودیعه.
        /// </summary>
        public static string Label_Mortgage {
            get {
                return ResourceManager.GetString("Label_Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت انعطاف در تبدیل اجاره / ودیعه وجود دارد.
        /// </summary>
        public static string Label_MortgageAndRentConvertible {
            get {
                return ResourceManager.GetString("Label_MortgageAndRentConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره ماهانه.
        /// </summary>
        public static string Label_Rent {
            get {
                return ResourceManager.GetString("Label_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مدت زمان قرارداد باید کمتر یا مساوی حداکثر زمان قرارداد باشد..
        /// </summary>
        public static string Validation_MinimumContractDuration_CompareToPropertyValue {
            get {
                return ResourceManager.GetString("Validation_MinimumContractDuration_CompareToPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ ودیعه باید کمتر یا مساوی مبلغ ودیعه فوق باشد..
        /// </summary>
        public static string Validation_MinimumMortgage_CompareToPropertyValue {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_CompareToPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_MinimumMortgage_Numeric {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_MinimumMortgage_Range {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ اجاره باید کمتر یا مساوی مبلغ اجاره فوق باشد..
        /// </summary>
        public static string Validation_MinimumRent_CompareToPropertyValue {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_CompareToPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_MinimumRent_Numeric {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_MinimumRent_Range {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_Mortgage_Numeric {
            get {
                return ResourceManager.GetString("Validation_Mortgage_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_Mortgage_Range {
            get {
                return ResourceManager.GetString("Validation_Mortgage_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_Rent_Numeric {
            get {
                return ResourceManager.GetString("Validation_Rent_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_Rent_Range {
            get {
                return ResourceManager.GetString("Validation_Rent_Range", resourceCulture);
            }
        }
    }
}
