//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertySalePaymentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertySalePaymentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Property.PropertySalePaymentResources", typeof(PropertySalePaymentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تقسیط در پرداخت قسمتی از مبلغ ملک وجود دارد.
        /// </summary>
        public static string Label_CanHaveDebt {
            get {
                return ResourceManager.GetString("Label_CanHaveDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تضمین مورد نیاز.
        /// </summary>
        public static string Label_DebtGuaranteeType {
            get {
                return ResourceManager.GetString("Label_DebtGuaranteeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک دارای وام قابل انتقال است.
        /// </summary>
        public static string Label_HasTransferableLoan {
            get {
                return ResourceManager.GetString("Label_HasTransferableLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل پرداخت ماهانه.
        /// </summary>
        public static string Label_MinimumMonthlyPaymentForDebt {
            get {
                return ResourceManager.GetString("Label_MinimumMonthlyPaymentForDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل پرداخت هنگام قرارداد.
        /// </summary>
        public static string Label_PaymentPercentForContract {
            get {
                return ResourceManager.GetString("Label_PaymentPercentForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد قابل تقسیط از مبلغ کل.
        /// </summary>
        public static string Label_PaymentPercentForDebt {
            get {
                return ResourceManager.GetString("Label_PaymentPercentForDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل پرداخت هنگام تحویل ملک.
        /// </summary>
        public static string Label_PaymentPercentForDelivery {
            get {
                return ResourceManager.GetString("Label_PaymentPercentForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر مربع زمین.
        /// </summary>
        public static string Label_PricePerEstateArea {
            get {
                return ResourceManager.GetString("Label_PricePerEstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر مربع از بنا.
        /// </summary>
        public static string Label_PricePerUnitArea {
            get {
                return ResourceManager.GetString("Label_PricePerUnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نحوه مشخص نمودن قیمت ملک را انتخاب کنید.
        /// </summary>
        public static string Label_PriceSpecificationType {
            get {
                return ResourceManager.GetString("Label_PriceSpecificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ باقی مانده از وام.
        /// </summary>
        public static string Label_TransferableLoanAmount {
            get {
                return ResourceManager.GetString("Label_TransferableLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_MinimumMonthlyPaymentForDebt_Numeric {
            get {
                return ResourceManager.GetString("Validation_MinimumMonthlyPaymentForDebt_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_MinimumMonthlyPaymentForDebt_Range {
            get {
                return ResourceManager.GetString("Validation_MinimumMonthlyPaymentForDebt_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PaymentPercentForContract_Numeric {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForContract_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PaymentPercentForContract_Range {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForContract_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PaymentPercentForDebt_Numeric {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForDebt_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PaymentPercentForDebt_Range {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForDebt_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PaymentPercentForDelivery_Numeric {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForDelivery_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PaymentPercentForDelivery_Range {
            get {
                return ResourceManager.GetString("Validation_PaymentPercentForDelivery_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_Price_Numeric {
            get {
                return ResourceManager.GetString("Validation_Price_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_Price_Range {
            get {
                return ResourceManager.GetString("Validation_Price_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PricePerEstateArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_PricePerEstateArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PricePerEstateArea_Range {
            get {
                return ResourceManager.GetString("Validation_PricePerEstateArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PricePerUnitArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_PricePerUnitArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PricePerUnitArea_Range {
            get {
                return ResourceManager.GetString("Validation_PricePerUnitArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_TransferableLoanAmount_Numeric {
            get {
                return ResourceManager.GetString("Validation_TransferableLoanAmount_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_TransferableLoanAmount_Range {
            get {
                return ResourceManager.GetString("Validation_TransferableLoanAmount_Range", resourceCulture);
            }
        }
    }
}
