//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyLuxuryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyLuxuryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Property.PropertyLuxuryResources", typeof(PropertyLuxuryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر امکانات و خصوصیات لوکس.
        /// </summary>
        public static string Label_AdditionalLuxuryFeatures {
            get {
                return ResourceManager.GetString("Label_AdditionalLuxuryFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع سقف.
        /// </summary>
        public static string Label_CeilingHeight {
            get {
                return ResourceManager.GetString("Label_CeilingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالکن چهار طرف دارد.
        /// </summary>
        public static string Label_HasAllSideBalcony {
            get {
                return ResourceManager.GetString("Label_HasAllSideBalcony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دید همه جهت دارد.
        /// </summary>
        public static string Label_HasAllSideView {
            get {
                return ResourceManager.GetString("Label_HasAllSideView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم کامپیوتری مدیریت ساختمان دارد.
        /// </summary>
        public static string Label_HasBuildingManagementSystem {
            get {
                return ResourceManager.GetString("Label_HasBuildingManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضای سبز در بالکن دارد.
        /// </summary>
        public static string Label_HasGardenInBalcony {
            get {
                return ResourceManager.GetString("Label_HasGardenInBalcony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوئیت مهمان دارد.
        /// </summary>
        public static string Label_HasGuestSuite {
            get {
                return ResourceManager.GetString("Label_HasGuestSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارکینگ داخل واحد دارد.
        /// </summary>
        public static string Label_HasInUnitParking {
            get {
                return ResourceManager.GetString("Label_HasInUnitParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیوار متحرک دارد.
        /// </summary>
        public static string Label_HasMobileWall {
            get {
                return ResourceManager.GetString("Label_HasMobileWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف بازشو دارد.
        /// </summary>
        public static string Label_HasOpenningCeiling {
            get {
                return ResourceManager.GetString("Label_HasOpenningCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسانسور اختصاصی دارد.
        /// </summary>
        public static string Label_HasPrivateElevator {
            get {
                return ResourceManager.GetString("Label_HasPrivateElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد سرایداری مجزا و اختصاصی دارد.
        /// </summary>
        public static string Label_HasPrivateJanitorUnit {
            get {
                return ResourceManager.GetString("Label_HasPrivateJanitorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخر اختصاصی دارد.
        /// </summary>
        public static string Label_HasPrivatePool {
            get {
                return ResourceManager.GetString("Label_HasPrivatePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریموت کنترل برای پرده ها دارد.
        /// </summary>
        public static string Label_HasRemoteControlledCurtains {
            get {
                return ResourceManager.GetString("Label_HasRemoteControlledCurtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق های مستر.
        /// </summary>
        public static string Label_NumberOfMasterBedrooms {
            get {
                return ResourceManager.GetString("Label_NumberOfMasterBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_CeilingHeight_Numeric {
            get {
                return ResourceManager.GetString("Validation_CeilingHeight_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_CeilingHeight_Range {
            get {
                return ResourceManager.GetString("Validation_CeilingHeight_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_NumberOfMasterBedrooms_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberOfMasterBedrooms_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_NumberOfMasterBedrooms_Range {
            get {
                return ResourceManager.GetString("Validation_NumberOfMasterBedrooms_Range", resourceCulture);
            }
        }
    }
}
