//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertySummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertySummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Property.PropertySummaryResources", typeof(PropertySummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر؛ فقط مشتریان نهایی مورد نظر هستند.
        /// </summary>
        public static string AgencyPropertyListingAgencyActivityAllowance_OtherAgencyNotPermitted {
            get {
                return ResourceManager.GetString("AgencyPropertyListingAgencyActivityAllowance_OtherAgencyNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله؛ در صورت عقد قرارداد کمیسیون را تقسیم می کنیم.
        /// </summary>
        public static string AgencyPropertyListingAgencyActivityAllowance_OtherAgencyPermitted {
            get {
                return ResourceManager.GetString("AgencyPropertyListingAgencyActivityAllowance_OtherAgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات آدرس (در صورت نیاز):.
        /// </summary>
        public static string Label_AdditionalAddressInfo {
            get {
                return ResourceManager.GetString("Label_AdditionalAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات، ویژگی ها و امتیازات واحد.
        /// </summary>
        public static string Label_AdditionalSpecialFeatures {
            get {
                return ResourceManager.GetString("Label_AdditionalSpecialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس:.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بنگاه.
        /// </summary>
        public static string Label_AgencyAddress {
            get {
                return ResourceManager.GetString("Label_AgencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا این آگهی توسط واسطه ثبت می شود؟.
        /// </summary>
        public static string Label_AgencyListing {
            get {
                return ResourceManager.GetString("Label_AgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا با سایر بنگاه های معاملات ملکی روی فروش یا اجاره این مورد همکاری می کنید؟.
        /// </summary>
        public static string Label_AgencyListing_OtherAgencyPermitted {
            get {
                return ResourceManager.GetString("Label_AgencyListing_OtherAgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بنگاه.
        /// </summary>
        public static string Label_AgencyName {
            get {
                return ResourceManager.GetString("Label_AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمر بنا.
        /// </summary>
        public static string Label_BuildingAgeYears {
            get {
                return ResourceManager.GetString("Label_BuildingAgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string Label_CityID {
            get {
                return ResourceManager.GetString("Label_CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه شهرداری.
        /// </summary>
        public static string Label_CityRegionID {
            get {
                return ResourceManager.GetString("Label_CityRegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Label_ContactEmail {
            get {
                return ResourceManager.GetString("Label_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص.
        /// </summary>
        public static string Label_ContactName {
            get {
                return ResourceManager.GetString("Label_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Label_ContactPhone1 {
            get {
                return ResourceManager.GetString("Label_ContactPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن دوم.
        /// </summary>
        public static string Label_ContactPhone2 {
            get {
                return ResourceManager.GetString("Label_ContactPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متراژ زمین.
        /// </summary>
        public static string Label_EstateArea {
            get {
                return ResourceManager.GetString("Label_EstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت زمین.
        /// </summary>
        public static string Label_EstateDirection {
            get {
                return ResourceManager.GetString("Label_EstateDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سند.
        /// </summary>
        public static string Label_EstateVoucherType {
            get {
                return ResourceManager.GetString("Label_EstateVoucherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نمای ساختمان.
        /// </summary>
        public static string Label_FaceType {
            get {
                return ResourceManager.GetString("Label_FaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درب پارکینگ ریموتی دارد.
        /// </summary>
        public static string Label_HasAutomaticParkingDoor {
            get {
                return ResourceManager.GetString("Label_HasAutomaticParkingDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز سازی شده است.
        /// </summary>
        public static string Label_HasBeenReconstructed {
            get {
                return ResourceManager.GetString("Label_HasBeenReconstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسانسور دارد.
        /// </summary>
        public static string Label_HasElevator {
            get {
                return ResourceManager.GetString("Label_HasElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستشویی فرنگی دارد.
        /// </summary>
        public static string Label_HasForeignLavatory {
            get {
                return ResourceManager.GetString("Label_HasForeignLavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن اجتماعات دارد.
        /// </summary>
        public static string Label_HasGatheringHall {
            get {
                return ResourceManager.GetString("Label_HasGatheringHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستشویی ایرانی دارد.
        /// </summary>
        public static string Label_HasIranianLavatory {
            get {
                return ResourceManager.GetString("Label_HasIranianLavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جکوزی دارد.
        /// </summary>
        public static string Label_HasJacuzzi {
            get {
                return ResourceManager.GetString("Label_HasJacuzzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسیوی اختصاصی دارد.
        /// </summary>
        public static string Label_HasPrivatePatio {
            get {
                return ResourceManager.GetString("Label_HasPrivatePatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سونا دارد.
        /// </summary>
        public static string Label_HasSauna {
            get {
                return ResourceManager.GetString("Label_HasSauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخر دارد.
        /// </summary>
        public static string Label_HasSwimmingPool {
            get {
                return ResourceManager.GetString("Label_HasSwimmingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک دارای وام قابل انتقال است.
        /// </summary>
        public static string Label_HasTransferableLoan {
            get {
                return ResourceManager.GetString("Label_HasTransferableLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیفون تصویری دارد.
        /// </summary>
        public static string Label_HasVideoEyePhone {
            get {
                return ResourceManager.GetString("Label_HasVideoEyePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت.
        /// </summary>
        public static string Label_IntentionOfOwner {
            get {
                return ResourceManager.GetString("Label_IntentionOfOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد دوبلکس است.
        /// </summary>
        public static string Label_IsDuplex {
            get {
                return ResourceManager.GetString("Label_IsDuplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس بدنه کابینت های آشپزخانه.
        /// </summary>
        public static string Label_KitchenCabinetBodyType {
            get {
                return ResourceManager.GetString("Label_KitchenCabinetBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس سطح کابینت های آشپزخانه.
        /// </summary>
        public static string Label_KitchenCabinetTopType {
            get {
                return ResourceManager.GetString("Label_KitchenCabinetTopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس کف پذیرایی.
        /// </summary>
        public static string Label_LivingRoomFloor {
            get {
                return ResourceManager.GetString("Label_LivingRoomFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت اصلی نور واحد.
        /// </summary>
        public static string Label_MainDaylightDirection {
            get {
                return ResourceManager.GetString("Label_MainDaylightDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ ودیعه.
        /// </summary>
        public static string Label_MinimumMortgage {
            get {
                return ResourceManager.GetString("Label_MinimumMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل اجاره ماهانه.
        /// </summary>
        public static string Label_MinimumRent {
            get {
                return ResourceManager.GetString("Label_MinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ودیعه.
        /// </summary>
        public static string Label_Mortgage {
            get {
                return ResourceManager.GetString("Label_Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره / ودیعه قابل تبدیل هستند.
        /// </summary>
        public static string Label_MortgageAndRentConvertible {
            get {
                return ResourceManager.GetString("Label_MortgageAndRentConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله.
        /// </summary>
        public static string Label_NeighborhoodID {
            get {
                return ResourceManager.GetString("Label_NeighborhoodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا بنگاه های معاملات ملکی می توانند روی فروش یا اجاره این مورد کار کنند؟.
        /// </summary>
        public static string Label_NoAgencyListing_AgencyPermitted {
            get {
                return ResourceManager.GetString("Label_NoAgencyListing_AgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقات ساختمان.
        /// </summary>
        public static string Label_NumberFloorsAboveGround {
            get {
                return ResourceManager.GetString("Label_NumberFloorsAboveGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق های مستر.
        /// </summary>
        public static string Label_NumberOfMasterBedrooms {
            get {
                return ResourceManager.GetString("Label_NumberOfMasterBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد پارکینگ ها.
        /// </summary>
        public static string Label_NumberOfParkings {
            get {
                return ResourceManager.GetString("Label_NumberOfParkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق ها.
        /// </summary>
        public static string Label_NumberOfRooms {
            get {
                return ResourceManager.GetString("Label_NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد واحدها در طبقه.
        /// </summary>
        public static string Label_NumberOfUnitsPerFloor {
            get {
                return ResourceManager.GetString("Label_NumberOfUnitsPerFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول بَر به گذر اصلی.
        /// </summary>
        public static string Label_PassageEdgeLength {
            get {
                return ResourceManager.GetString("Label_PassageEdgeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر زمین.
        /// </summary>
        public static string Label_PricePerEstateArea {
            get {
                return ResourceManager.GetString("Label_PricePerEstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر زیربنا.
        /// </summary>
        public static string Label_PricePerUnitArea {
            get {
                return ResourceManager.GetString("Label_PricePerUnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیوه مشخص کردن قیمت.
        /// </summary>
        public static string Label_PriceSpecificationType {
            get {
                return ResourceManager.GetString("Label_PriceSpecificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملک.
        /// </summary>
        public static string Label_PropertyType {
            get {
                return ResourceManager.GetString("Label_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Label_ProvinceID {
            get {
                return ResourceManager.GetString("Label_ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان عمومی بودن آگهی روی اینترنت.
        /// </summary>
        public static string Label_PublishDuration {
            get {
                return ResourceManager.GetString("Label_PublishDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره ماهانه.
        /// </summary>
        public static string Label_Rent {
            get {
                return ResourceManager.GetString("Label_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت انباری ها.
        /// </summary>
        public static string Label_StorageRoomArea {
            get {
                return ResourceManager.GetString("Label_StorageRoomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد واحدها در ساختمان.
        /// </summary>
        public static string Label_TotalNumberOfUnits {
            get {
                return ResourceManager.GetString("Label_TotalNumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ باقی مانده از وام.
        /// </summary>
        public static string Label_TransferableLoanAmount {
            get {
                return ResourceManager.GetString("Label_TransferableLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیربنا.
        /// </summary>
        public static string Label_UnitArea {
            get {
                return ResourceManager.GetString("Label_UnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه.
        /// </summary>
        public static string Label_UnitFloorNumber {
            get {
                return ResourceManager.GetString("Label_UnitFloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری.
        /// </summary>
        public static string Label_UnitUsageType {
            get {
                return ResourceManager.GetString("Label_UnitUsageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر؛ فقط قرارداد بی واسطه مورد نظر است.
        /// </summary>
        public static string NonAgencyPropertyListingAgencyActivityAllowance_AgencyNotPermitted {
            get {
                return ResourceManager.GetString("NonAgencyPropertyListingAgencyActivityAllowance_AgencyNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله؛ در صورت عقد قرارداد کمیسیون دریافت می کنند.
        /// </summary>
        public static string NonAgencyPropertyListingAgencyActivityAllowance_AgencyPermitted {
            get {
                return ResourceManager.GetString("NonAgencyPropertyListingAgencyActivityAllowance_AgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آگهی توسط مشاور ثبت می شود..
        /// </summary>
        public static string PropertyListingCreatorRoleType_AgencyListing {
            get {
                return ResourceManager.GetString("PropertyListingCreatorRoleType_AgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آگهی بی واسطه است..
        /// </summary>
        public static string PropertyListingCreatorRoleType_NoAgencyListing {
            get {
                return ResourceManager.GetString("PropertyListingCreatorRoleType_NoAgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج ماه عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_FiveMonths {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_FiveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار روز عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_FourDays {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_FourDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار ماه عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_FourMonths {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_FourMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ماه عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_OneMonth {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک هفته عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_OneWeek {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه ماه عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_ThreeMonths {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه هفته عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_ThreeWeeks {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_ThreeWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو روز عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_TwoDays {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو ماه عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_TwoMonths {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو هفته عمومی باشد.
        /// </summary>
        public static string PropertyPublishDurationEnum_TwoWeeks {
            get {
                return ResourceManager.GetString("PropertyPublishDurationEnum_TwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_BuildingAgeYears_Numeric {
            get {
                return ResourceManager.GetString("Validation_BuildingAgeYears_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_BuildingAgeYears_Range {
            get {
                return ResourceManager.GetString("Validation_BuildingAgeYears_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید حاوی یک آدرس ایمیل معتبر باشد..
        /// </summary>
        public static string Validation_ContactEmail_Email {
            get {
                return ResourceManager.GetString("Validation_ContactEmail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن به طور صحیح وارد نشده است..
        /// </summary>
        public static string Validation_ContactPhone1_PhoneNumber {
            get {
                return ResourceManager.GetString("Validation_ContactPhone1_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن به طور صحیح وارد نشده است..
        /// </summary>
        public static string Validation_ContactPhone2_PhoneNumber {
            get {
                return ResourceManager.GetString("Validation_ContactPhone2_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت باید به صورت یک عدد وارد شود..
        /// </summary>
        public static string Validation_EstateArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_EstateArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_EstateArea_Range {
            get {
                return ResourceManager.GetString("Validation_EstateArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ ودیعه باید کمتر یا مساوی مبلغ ودیعه فوق باشد..
        /// </summary>
        public static string Validation_MinimumMortgage_CompareToPropertyValue {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_CompareToPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_MinimumMortgage_Numeric {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_MinimumMortgage_Range {
            get {
                return ResourceManager.GetString("Validation_MinimumMortgage_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ اجاره باید کمتر یا مساوی مبلغ اجاره فوق باشد..
        /// </summary>
        public static string Validation_MinimumRent_CompareToPropertyValue {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_CompareToPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_MinimumRent_Numeric {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_MinimumRent_Range {
            get {
                return ResourceManager.GetString("Validation_MinimumRent_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_Mortgage_Numeric {
            get {
                return ResourceManager.GetString("Validation_Mortgage_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_Mortgage_Range {
            get {
                return ResourceManager.GetString("Validation_Mortgage_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_NumberFloorsAboveGround_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberFloorsAboveGround_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_NumberFloorsAboveGround_Range {
            get {
                return ResourceManager.GetString("Validation_NumberFloorsAboveGround_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_NumberOfMasterBedrooms_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberOfMasterBedrooms_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_NumberOfMasterBedrooms_Range {
            get {
                return ResourceManager.GetString("Validation_NumberOfMasterBedrooms_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_NumberOfParkings_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberOfParkings_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_NumberOfParkings_Range {
            get {
                return ResourceManager.GetString("Validation_NumberOfParkings_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_NumberOfRooms_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberOfRooms_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_NumberOfRooms_Range {
            get {
                return ResourceManager.GetString("Validation_NumberOfRooms_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_NumberOfUnitsPerFloor_Numeric {
            get {
                return ResourceManager.GetString("Validation_NumberOfUnitsPerFloor_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_NumberOfUnitsPerFloor_Range {
            get {
                return ResourceManager.GetString("Validation_NumberOfUnitsPerFloor_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_PassageEdgeLength_Numeric {
            get {
                return ResourceManager.GetString("Validation_PassageEdgeLength_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PassageEdgeLength_Range {
            get {
                return ResourceManager.GetString("Validation_PassageEdgeLength_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_Price_Numeric {
            get {
                return ResourceManager.GetString("Validation_Price_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_Price_Range {
            get {
                return ResourceManager.GetString("Validation_Price_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PricePerEstateArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_PricePerEstateArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PricePerEstateArea_Range {
            get {
                return ResourceManager.GetString("Validation_PricePerEstateArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_PricePerUnitArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_PricePerUnitArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_PricePerUnitArea_Range {
            get {
                return ResourceManager.GetString("Validation_PricePerUnitArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عدد باشد..
        /// </summary>
        public static string Validation_Rent_Numeric {
            get {
                return ResourceManager.GetString("Validation_Rent_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده قابل قبول است..
        /// </summary>
        public static string Validation_Rent_Range {
            get {
                return ResourceManager.GetString("Validation_Rent_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون مشخص کردن نوع واسط ثبت ملک امکان پذیر نیست.
        /// </summary>
        public static string Validation_Required_AgencyListing {
            get {
                return ResourceManager.GetString("Validation_Required_AgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون مشخص کردن نوع معامله ثبت ملک امکان پذیر نیست.
        /// </summary>
        public static string Validation_Required_IntentionOfOwner {
            get {
                return ResourceManager.GetString("Validation_Required_IntentionOfOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون مشخص کردن نوع ملک ثبت ملک امکان پذیر نیست.
        /// </summary>
        public static string Validation_Required_PropertyType {
            get {
                return ResourceManager.GetString("Validation_Required_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_StorageRoomArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_StorageRoomArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_StorageRoomArea_Range {
            get {
                return ResourceManager.GetString("Validation_StorageRoomArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_TotalNumberOfUnits_Numeric {
            get {
                return ResourceManager.GetString("Validation_TotalNumberOfUnits_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_TotalNumberOfUnits_Range {
            get {
                return ResourceManager.GetString("Validation_TotalNumberOfUnits_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_TransferableLoanAmount_Numeric {
            get {
                return ResourceManager.GetString("Validation_TransferableLoanAmount_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_TransferableLoanAmount_Range {
            get {
                return ResourceManager.GetString("Validation_TransferableLoanAmount_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_UnitArea_Numeric {
            get {
                return ResourceManager.GetString("Validation_UnitArea_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_UnitArea_Range {
            get {
                return ResourceManager.GetString("Validation_UnitArea_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره طبقه را باید به صورت عددی وارد نمایید..
        /// </summary>
        public static string Validation_UnitFloorNumber_Numeric {
            get {
                return ResourceManager.GetString("Validation_UnitFloorNumber_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده خارج از محدوده مجاز است..
        /// </summary>
        public static string Validation_UnitFloorNumber_Range {
            get {
                return ResourceManager.GetString("Validation_UnitFloorNumber_Range", resourceCulture);
            }
        }
    }
}
