//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountLogOnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountLogOnResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Account.AccountLogOnResources", typeof(AccountLogOnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to املاکی که در این جلسه به آنها دسترسی دارم به حسابم تخصیص داده شود.
        /// </summary>
        public static string Label_AcquireOwnedProperties {
            get {
                return ResourceManager.GetString("Label_AcquireOwnedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر.
        /// </summary>
        public static string Label_LoginName {
            get {
                return ResourceManager.GetString("Label_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روی این کامپیوتر، منو یادت نگه دار (روی کامپیوتر های عمومی از این گزینه استفاده نکنید).
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول شناسه کاربری، 4 حرف است..
        /// </summary>
        public static string Validation_Length_LoginName {
            get {
                return ResourceManager.GetString("Validation_Length_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول کلمه عبور، 4 حرف است..
        /// </summary>
        public static string Validation_Length_Password {
            get {
                return ResourceManager.GetString("Validation_Length_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شناسه کاربری را وارد کنید..
        /// </summary>
        public static string Validation_Required_LoginName {
            get {
                return ResourceManager.GetString("Validation_Required_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً کلمه عبور را وارد کنید..
        /// </summary>
        public static string Validation_Required_Password {
            get {
                return ResourceManager.GetString("Validation_Required_Password", resourceCulture);
            }
        }
    }
}
