//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountForgotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountForgotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Account.AccountForgotResources", typeof(AccountForgotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور جدید.
        /// </summary>
        public static string Label_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Label_LoginName {
            get {
                return ResourceManager.GetString("Label_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز ارسال شده.
        /// </summary>
        public static string Label_PasswordResetToken {
            get {
                return ResourceManager.GetString("Label_PasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Label_VerificationEmailAddress {
            get {
                return ResourceManager.GetString("Label_VerificationEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه.
        /// </summary>
        public static string Label_VerificationPhoneNumber {
            get {
                return ResourceManager.GetString("Label_VerificationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر دو کلمه عبور وارد شده باید با هم برابر باشند..
        /// </summary>
        public static string Validation_ConfirmNewPassword_Compare {
            get {
                return ResourceManager.GetString("Validation_ConfirmNewPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه نام کاربری الزامی است.
        /// </summary>
        public static string Validation_LoginName_Required {
            get {
                return ResourceManager.GetString("Validation_LoginName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور نمی تواند کمتر از 4 حرف باشد، و بهتر است بیش از 6 حرف باشد..
        /// </summary>
        public static string Validation_NewPassword_Length {
            get {
                return ResourceManager.GetString("Validation_NewPassword_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یک کلمه عبور جدید انتخاب کنید.
        /// </summary>
        public static string Validation_NewPassword_Required {
            get {
                return ResourceManager.GetString("Validation_NewPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت تنظیم مجدد کلمه عبور، لطفاً رمز ارسال شده را ارائه کنید..
        /// </summary>
        public static string Validation_PasswordResetToken_Required {
            get {
                return ResourceManager.GetString("Validation_PasswordResetToken_Required", resourceCulture);
            }
        }
    }
}
