//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewPropertyUnitResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewPropertyUnitResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View.ViewPropertyUnitRes" +
                            "ources", typeof(ViewPropertyUnitResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} متر مربع.
        /// </summary>
        public static string BalconyArea {
            get {
                return ResourceManager.GetString("BalconyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string CurrentMonthlyChargeAmount {
            get {
                return ResourceManager.GetString("CurrentMonthlyChargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوبلکس.
        /// </summary>
        public static string Duplex {
            get {
                return ResourceManager.GetString("Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واقع در طبقه {0}.
        /// </summary>
        public static string FloorNumber {
            get {
                return ResourceManager.GetString("FloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبله کامل.
        /// </summary>
        public static string Furnished {
            get {
                return ResourceManager.GetString("Furnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با نیم طبقه داخلی.
        /// </summary>
        public static string HalfFloorInside {
            get {
                return ResourceManager.GetString("HalfFloorInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} متر مربع.
        /// </summary>
        public static string KitchenArea {
            get {
                return ResourceManager.GetString("KitchenArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} بالکن.
        /// </summary>
        public static string NumberOfBalconies {
            get {
                return ResourceManager.GetString("NumberOfBalconies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} حمام.
        /// </summary>
        public static string NumberOfBathrooms {
            get {
                return ResourceManager.GetString("NumberOfBathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} درب کمد.
        /// </summary>
        public static string NumberOfClosets {
            get {
                return ResourceManager.GetString("NumberOfClosets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} آشپزخانه.
        /// </summary>
        public static string NumberOfKitchens {
            get {
                return ResourceManager.GetString("NumberOfKitchens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دستشویی.
        /// </summary>
        public static string NumberOfLavatories {
            get {
                return ResourceManager.GetString("NumberOfLavatories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} پارکینگ.
        /// </summary>
        public static string NumberOfParkings {
            get {
                return ResourceManager.GetString("NumberOfParkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} اتاق.
        /// </summary>
        public static string NumberOfRooms {
            get {
                return ResourceManager.GetString("NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق ها مشخص نشده است..
        /// </summary>
        public static string NumberOfRoomsNotSpecified {
            get {
                return ResourceManager.GetString("NumberOfRoomsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} متر مربع.
        /// </summary>
        public static string StorageRoomArea {
            get {
                return ResourceManager.GetString("StorageRoomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای {0}.
        /// </summary>
        public static string UnitIncludes {
            get {
                return ResourceManager.GetString("UnitIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصیات اصلی واحد مشخص نشده است.
        /// </summary>
        public static string UnitPropertiesNotSet {
            get {
                return ResourceManager.GetString("UnitPropertiesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد {0}.
        /// </summary>
        public static string UsageType {
            get {
                return ResourceManager.GetString("UsageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با مساحت {0:#.##} متر مربع.
        /// </summary>
        public static string UsefulArea {
            get {
                return ResourceManager.GetString("UsefulArea", resourceCulture);
            }
        }
    }
}
