//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewPropertyPaymentConditionsForSaleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewPropertyPaymentConditionsForSaleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View.ViewPropertyPayment" +
                            "ConditionsForSaleResources", typeof(ViewPropertyPaymentConditionsForSaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادل {0} تومان.
        /// </summary>
        public static string CalculatedMaximumDebt {
            get {
                return ResourceManager.GetString("CalculatedMaximumDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادل {0} تومان.
        /// </summary>
        public static string CalculatedPaymentForContract {
            get {
                return ResourceManager.GetString("CalculatedPaymentForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادل {0} تومان.
        /// </summary>
        public static string CalculatedPaymentForDelivery {
            get {
                return ResourceManager.GetString("CalculatedPaymentForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string MinimumMonthlyPaymentForDebt {
            get {
                return ResourceManager.GetString("MinimumMonthlyPaymentForDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} درصد.
        /// </summary>
        public static string PaymentPercentForContract {
            get {
                return ResourceManager.GetString("PaymentPercentForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} درصد.
        /// </summary>
        public static string PaymentPercentForDebt {
            get {
                return ResourceManager.GetString("PaymentPercentForDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} درصد.
        /// </summary>
        public static string PaymentPercentForDelivery {
            get {
                return ResourceManager.GetString("PaymentPercentForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string PricePerEstateArea {
            get {
                return ResourceManager.GetString("PricePerEstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string PricePerUnitArea {
            get {
                return ResourceManager.GetString("PricePerUnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت ملک مشخص نشده است..
        /// </summary>
        public static string PriceSpecificationTypeNotSpecified {
            get {
                return ResourceManager.GetString("PriceSpecificationTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تومان.
        /// </summary>
        public static string TransferableLoanAmount {
            get {
                return ResourceManager.GetString("TransferableLoanAmount", resourceCulture);
            }
        }
    }
}
