//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewPropertyBuildingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewPropertyBuildingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View.ViewPropertyBuildin" +
                            "gResources", typeof(ViewPropertyBuildingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} سال.
        /// </summary>
        public static string BuildingAgeYears {
            get {
                return ResourceManager.GetString("BuildingAgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} طبقه.
        /// </summary>
        public static string NumberOfParkingFloors {
            get {
                return ResourceManager.GetString("NumberOfParkingFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} طبقه.
        /// </summary>
        public static string NumberOfUnitFloors {
            get {
                return ResourceManager.GetString("NumberOfUnitFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} واحد.
        /// </summary>
        public static string NumberOfUnitsPerFloor {
            get {
                return ResourceManager.GetString("NumberOfUnitsPerFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} واحد.
        /// </summary>
        public static string TotalNumberOfUnits {
            get {
                return ResourceManager.GetString("TotalNumberOfUnits", resourceCulture);
            }
        }
    }
}
