//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewPropertyLocationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewPropertyLocationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Views.Shared.Property.View.ViewPropertyLocatio" +
                            "nResources", typeof(ViewPropertyLocationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات آدرس: {0}.
        /// </summary>
        public static string AdditionalAddressInfo {
            get {
                return ResourceManager.GetString("AdditionalAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (آدرس کامل پس از تماس ارائه می شود).
        /// </summary>
        public static string AddressIsNotComplete {
            get {
                return ResourceManager.GetString("AddressIsNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مشخص نشده است..
        /// </summary>
        public static string AddressNotSpecified {
            get {
                return ResourceManager.GetString("AddressNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلوک {0}.
        /// </summary>
        public static string BlockNo {
            get {
                return ResourceManager.GetString("BlockNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر و محله مشخص نشده است..
        /// </summary>
        public static string CityAndRegionNotSpecified {
            get {
                return ResourceManager.GetString("CityAndRegionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد {0}.
        /// </summary>
        public static string FlatNo {
            get {
                return ResourceManager.GetString("FlatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه {0}.
        /// </summary>
        public static string FloorNo {
            get {
                return ResourceManager.GetString("FloorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک {0}.
        /// </summary>
        public static string PlateNo {
            get {
                return ResourceManager.GetString("PlateNo", resourceCulture);
            }
        }
    }
}
