//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesSaveSearchResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesSaveSearchResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Properties.PropertiesSaveSearchResource" +
                            "s", typeof(PropertiesSaveSearchResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان دریافت پیغام.
        /// </summary>
        public static string Label_DaysToKeepSendingNotificatons {
            get {
                return ResourceManager.GetString("Label_DaysToKeepSendingNotificatons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل جهت اطلاع رسانی.
        /// </summary>
        public static string Label_EmailNotificationTargetID {
            get {
                return ResourceManager.GetString("Label_EmailNotificationTargetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاع رسانی املاک ثبت شده از طریق ایمیل.
        /// </summary>
        public static string Label_SendNotificationEmails {
            get {
                return ResourceManager.GetString("Label_SendNotificationEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاع رسانی املاک ثبت شده از طریق پیامک.
        /// </summary>
        public static string Label_SendPaidSmsMessages {
            get {
                return ResourceManager.GetString("Label_SendPaidSmsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کننده ملکی که با شرایط من مطابقت دارد اجازه دارد به صورت پیامک به من اطلاع رسانی کند.
        /// </summary>
        public static string Label_SendPromotionalSmsMessages {
            get {
                return ResourceManager.GetString("Label_SendPromotionalSmsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن برای اطلاع رسانی.
        /// </summary>
        public static string Label_SmsNotificationTargetID {
            get {
                return ResourceManager.GetString("Label_SmsNotificationTargetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت (زیربنا و زمین).
        /// </summary>
        public static string Label_SmsPartArea {
            get {
                return ResourceManager.GetString("Label_SmsPartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص آگهی دهنده.
        /// </summary>
        public static string Label_SmsPartContactName {
            get {
                return ResourceManager.GetString("Label_SmsPartContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن ثبت شده روی آگهی.
        /// </summary>
        public static string Label_SmsPartContactPhone {
            get {
                return ResourceManager.GetString("Label_SmsPartContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن دوم ثبت شده روی آگهی.
        /// </summary>
        public static string Label_SmsPartContactSecondPhone {
            get {
                return ResourceManager.GetString("Label_SmsPartContactSecondPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملک در سایت.
        /// </summary>
        public static string Label_SmsPartListingCode {
            get {
                return ResourceManager.GetString("Label_SmsPartListingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اینترنتی مشخصات ملک.
        /// </summary>
        public static string Label_SmsPartListingUrl {
            get {
                return ResourceManager.GetString("Label_SmsPartListingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه جغرافیایی کامل.
        /// </summary>
        public static string Label_SmsPartLongGeographicRegion {
            get {
                return ResourceManager.GetString("Label_SmsPartLongGeographicRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد خواب / اتاق.
        /// </summary>
        public static string Label_SmsPartNumberOfRooms {
            get {
                return ResourceManager.GetString("Label_SmsPartNumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر از بنا یا زمین.
        /// </summary>
        public static string Label_SmsPartPerAreaPrice {
            get {
                return ResourceManager.GetString("Label_SmsPartPerAreaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش یا مبلغ اجاره.
        /// </summary>
        public static string Label_SmsPartPriceOrRent {
            get {
                return ResourceManager.GetString("Label_SmsPartPriceOrRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملک و کاربری.
        /// </summary>
        public static string Label_SmsPartPropertyType {
            get {
                return ResourceManager.GetString("Label_SmsPartPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محله یا منطقه.
        /// </summary>
        public static string Label_SmsPartShortGeographicRegion {
            get {
                return ResourceManager.GetString("Label_SmsPartShortGeographicRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سایت.
        /// </summary>
        public static string Label_SmsPartSiteName {
            get {
                return ResourceManager.GetString("Label_SmsPartSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وارد شده توسط کاربر (در صورت وجود).
        /// </summary>
        public static string Label_SmsPartUserEnteredAddress {
            get {
                return ResourceManager.GetString("Label_SmsPartUserEnteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_DaysToKeepSendingNotificatons_Numeric {
            get {
                return ResourceManager.GetString("Validation_DaysToKeepSendingNotificatons_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده در محدوده مجاز نیست.
        /// </summary>
        public static string Validation_DaysToKeepSendingNotificatons_Range {
            get {
                return ResourceManager.GetString("Validation_DaysToKeepSendingNotificatons_Range", resourceCulture);
            }
        }
    }
}
