//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesSearchResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesSearchResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Models.Properties.PropertiesSearchResources", typeof(PropertiesSearchResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط واسطه.
        /// </summary>
        public static string Label_AgencyListing {
            get {
                return ResourceManager.GetString("Label_AgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string Label_CityID {
            get {
                return ResourceManager.GetString("Label_CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_EstateAreaMaximum {
            get {
                return ResourceManager.GetString("Label_EstateAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت زمین از.
        /// </summary>
        public static string Label_EstateAreaMinimum {
            get {
                return ResourceManager.GetString("Label_EstateAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای.
        /// </summary>
        public static string Label_IntentionOfOwner {
            get {
                return ResourceManager.GetString("Label_IntentionOfOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله ها.
        /// </summary>
        public static string Label_NeighborhoodIDs {
            get {
                return ResourceManager.GetString("Label_NeighborhoodIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_NumberOfRoomsMaximum {
            get {
                return ResourceManager.GetString("Label_NumberOfRoomsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اتاق از.
        /// </summary>
        public static string Label_NumberOfRoomsMinimum {
            get {
                return ResourceManager.GetString("Label_NumberOfRoomsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملک.
        /// </summary>
        public static string Label_PropertyType {
            get {
                return ResourceManager.GetString("Label_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Label_ProvinceID {
            get {
                return ResourceManager.GetString("Label_ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_RentMaximum {
            get {
                return ResourceManager.GetString("Label_RentMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره ماهانه از.
        /// </summary>
        public static string Label_RentMinimum {
            get {
                return ResourceManager.GetString("Label_RentMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_RentMortgageMaximum {
            get {
                return ResourceManager.GetString("Label_RentMortgageMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ودیعه از.
        /// </summary>
        public static string Label_RentMortgageMinimum {
            get {
                return ResourceManager.GetString("Label_RentMortgageMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_SalePriceMaximum {
            get {
                return ResourceManager.GetString("Label_SalePriceMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل از.
        /// </summary>
        public static string Label_SalePriceMinimum {
            get {
                return ResourceManager.GetString("Label_SalePriceMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_SalePricePerEstateAreaMaximum {
            get {
                return ResourceManager.GetString("Label_SalePricePerEstateAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر زمین از.
        /// </summary>
        public static string Label_SalePricePerEstateAreaMinimum {
            get {
                return ResourceManager.GetString("Label_SalePricePerEstateAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_SalePricePerUnitAreaMaximum {
            get {
                return ResourceManager.GetString("Label_SalePricePerUnitAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر بنا از.
        /// </summary>
        public static string Label_SalePricePerUnitAreaMinimum {
            get {
                return ResourceManager.GetString("Label_SalePricePerUnitAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آسانسور.
        /// </summary>
        public static string Label_ShouldHaveElevator {
            get {
                return ResourceManager.GetString("Label_ShouldHaveElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پارکینگ.
        /// </summary>
        public static string Label_ShouldHaveParking {
            get {
                return ResourceManager.GetString("Label_ShouldHaveParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط نمایش رکورد های عکس دار.
        /// </summary>
        public static string Label_ShouldHavePhotos {
            get {
                return ResourceManager.GetString("Label_ShouldHavePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای انباری.
        /// </summary>
        public static string Label_ShouldHaveStorageRoom {
            get {
                return ResourceManager.GetString("Label_ShouldHaveStorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string Label_UnitAreaMaximum {
            get {
                return ResourceManager.GetString("Label_UnitAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت بنا از.
        /// </summary>
        public static string Label_UnitAreaMinimum {
            get {
                return ResourceManager.GetString("Label_UnitAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله ها.
        /// </summary>
        public static string Label_VicinityIDs {
            get {
                return ResourceManager.GetString("Label_VicinityIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_Area_Numeric {
            get {
                return ResourceManager.GetString("Validation_Area_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده در محدوده مجاز نیست.
        /// </summary>
        public static string Validation_Area_Range {
            get {
                return ResourceManager.GetString("Validation_Area_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مبلغ را به صورت عددی وارد کنید.
        /// </summary>
        public static string Validation_Price_Numeric {
            get {
                return ResourceManager.GetString("Validation_Price_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده در محدوده مجاز نیست.
        /// </summary>
        public static string Validation_Price_Range {
            get {
                return ResourceManager.GetString("Validation_Price_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد..
        /// </summary>
        public static string Validation_Rooms_Numeric {
            get {
                return ResourceManager.GetString("Validation_Rooms_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده در محدوده مجاز نیست.
        /// </summary>
        public static string Validation_Rooms_Range {
            get {
                return ResourceManager.GetString("Validation_Rooms_Range", resourceCulture);
            }
        }
    }
}
