// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1131));
        
        string IMigrationMetadata.Id
        {
            get { return "201309191333015_1.1.3.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
