// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _1132 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1132));
        
        string IMigrationMetadata.Id
        {
            get { return "201311171200054_1.1.3.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
