// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1071 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1071));
        
        string IMigrationMetadata.Id
        {
            get { return "201304162223397_1.0.7.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
