// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _141Sponsorship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_141Sponsorship));
        
        string IMigrationMetadata.Id
        {
            get { return "201404281152273_1.4.1.Sponsorship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
