// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _1631 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1631));
        
        string IMigrationMetadata.Id
        {
            get { return "201411131202317_1.6.3.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
