namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _155EfIndexBug : DbMigration
    {
        public override void Up()
        {
			DropIndex("dbo.ProvinceAdjacencies", new[] { "AdjacentProvinceID" });
			DropIndex("dbo.ProvinceAdjacencies", new[] { "BaseProvinceID" });
			DropIndex("dbo.NeighborhoodSynonyms", new[] { "SynonymNeighborhoodID" });
			DropIndex("dbo.NeighborhoodSynonyms", new[] { "BaseNeighborhoodID" });
			DropIndex("dbo.CityRegionNeighborhoodRelation", new[] { "Neighborhood_ID" });
			DropIndex("dbo.CityRegionNeighborhoodRelation", new[] { "CityRegion_ID" });
			DropIndex("dbo.CityRegionAdjacencies", new[] { "AdjacentCityRegionID" });
			DropIndex("dbo.CityRegionAdjacencies", new[] { "BaseCityRegionID" });
			DropIndex("dbo.NeighborhoodAdjacencies", new[] { "AdjacentNeighborhoodID" });
			DropIndex("dbo.NeighborhoodAdjacencies", new[] { "BaseNeighborhoodID" });
			DropIndex("dbo.CityAdjacencies", new[] { "AdjacentCityID" });
			DropIndex("dbo.CityAdjacencies", new[] { "BaseCityID" });
			DropIndex("dbo.UserWireTransferPayment", new[] { "ReverseTransactionID" });
			DropIndex("dbo.UserWireTransferPayment", new[] { "ForwardTransactionID" });
			DropIndex("dbo.UserWireTransferPayment", new[] { "TargetUserID" });
			DropIndex("dbo.UserWireTransferPayment", new[] { "ReviewedByUserID" });
			DropIndex("dbo.UserRefundRequest", new[] { "ReverseTransactionID" });
			DropIndex("dbo.UserRefundRequest", new[] { "ForwardTransactionID" });
			DropIndex("dbo.UserRefundRequest", new[] { "TargetUserID" });
			DropIndex("dbo.UserRefundRequest", new[] { "ClearedByUserID" });
			DropIndex("dbo.UserRefundRequest", new[] { "ReviewedByUserID" });
			DropIndex("dbo.UserElectronicPayment", new[] { "ReverseTransactionID" });
			DropIndex("dbo.UserElectronicPayment", new[] { "ForwardTransactionID" });
			DropIndex("dbo.UserElectronicPayment", new[] { "TargetUserID" });
			DropIndex("dbo.UserElectronicPayment", new[] { "ReviewedByUserID" });
			DropIndex("dbo.UserContactMethodVerification", new[] { "TargetContactMethodID" });
			DropIndex("dbo.UserContactMethodVerification", new[] { "TargetUserID" });
			DropIndex("dbo.UserContactMethodVerification", new[] { "SessionID" });
			DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ReverseTransactionID" });
			DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ForwardTransactionID" });
			DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "TargetUserID" });
			DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ReviewedByUserID" });
			DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "CreatedByUserID" });
			DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "UserID" });
			DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "SessionID" });
			DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "SavedSearchID" });
			DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "ReverseTransactionID" });
			DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "ForwardTransactionID" });
			DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "TargetUserID" });
			DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "BillingID" });
			DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "TargetUserID" });
			DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "ContactMethodID" });
			DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "SavedSearchID" });
			DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "PropertyListingID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "ReverseTransactionID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "ForwardTransactionID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "TargetUserID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "PromotionalSmsID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "PropertyListingID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "ReverseTransactionID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "ForwardTransactionID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "TargetUserID" });
			DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "PropertyListingID" });
			DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "VicinityID" });
			DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "NeighborhoodID" });
			DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "PropertySearchID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "SmsNotificationTargetID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "EmailNotificationTargetID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "CityRegionID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "CityID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "ProvinceID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "CreatorSessionID" });
			DropIndex("dbo.SavedPropertySearch", new[] { "UserID" });
			DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "ContactMethodID" });
			DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "SavedSearchID" });
			DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "PropertyListingID" });
			DropIndex("dbo.PropertySearchHistory", new[] { "UserID" });
			DropIndex("dbo.PropertySearchHistory", new[] { "SessionID" });
			DropIndex("dbo.PropertyRequest", new[] { "OwnerUserID" });
			DropIndex("dbo.PropertyRequest", new[] { "CreatorUserID" });
			DropIndex("dbo.PropertyRequest", new[] { "CreatorSessionID" });
			DropIndex("dbo.PropertyListingUpdateHistory", new[] { "UserID" });
			DropIndex("dbo.PropertyListingUpdateHistory", new[] { "SessionID" });
			DropIndex("dbo.PropertyListingUpdateHistory", new[] { "PropertyListingID" });
			DropIndex("dbo.PropertyListingPublishHistory", new[] { "UserID" });
			DropIndex("dbo.PropertyListingPublishHistory", new[] { "SessionID" });
			DropIndex("dbo.PropertyListingPublishHistory", new[] { "PropertyListingID" });
			DropIndex("dbo.PromotionalBonus", new[] { "ReverseTransactionID" });
			DropIndex("dbo.PromotionalBonus", new[] { "ForwardTransactionID" });
			DropIndex("dbo.PromotionalBonus", new[] { "TargetUserID" });
			DropIndex("dbo.PromotionalBonus", new[] { "CreatedByUserID" });
			DropIndex("dbo.PromotionalBonusCoupon", new[] { "ReverseTransactionID" });
			DropIndex("dbo.PromotionalBonusCoupon", new[] { "ForwardTransactionID" });
			DropIndex("dbo.PromotionalBonusCoupon", new[] { "TargetUserID" });
			DropIndex("dbo.PromotionalBonusCoupon", new[] { "CreatedByUserID" });
			DropIndex("dbo.PasswordResetRequest", new[] { "ContactMethodID" });
			DropIndex("dbo.PasswordResetRequest", new[] { "TargetUserID" });
			DropIndex("dbo.PasswordResetRequest", new[] { "SessionID" });
			DropIndex("dbo.OutgoingSmsMessage", new[] { "RetryForMessageID" });
			DropIndex("dbo.OutgoingSmsMessage", new[] { "NotificationID" });
			DropIndex("dbo.OutgoingSmsMessage", new[] { "TargetUserID" });
			DropIndex("dbo.NotificationMessage", new[] { "TargetUserID" });
			DropIndex("dbo.LoginNameQuery", new[] { "ContactMethodID" });
			DropIndex("dbo.LoginNameQuery", new[] { "TargetUserID" });
			DropIndex("dbo.LoginNameQuery", new[] { "SessionID" });
			DropIndex("dbo.ArticleSet", new[] { "LastModifiedByUserID" });
			DropIndex("dbo.ArticleSet", new[] { "CreatedByUserID" });
			DropIndex("dbo.ArticleSet", new[] { "OwnerUserID" });
			DropIndex("dbo.ArticleSet", new[] { "CategoryID" });
			DropIndex("dbo.ArticleRevision", new[] { "PublishedByUserID" });
			DropIndex("dbo.ArticleRevision", new[] { "FinalizedByUserID" });
			DropIndex("dbo.ArticleRevision", new[] { "LastModifiedByUserID" });
			DropIndex("dbo.ArticleRevision", new[] { "CreatedByUserID" });
			DropIndex("dbo.ArticleRevision", new[] { "ArticleID" });
			DropIndex("dbo.Article", new[] { "LastModifiedByUserID" });
			DropIndex("dbo.Article", new[] { "CreatedByUserID" });
			DropIndex("dbo.Article", new[] { "OwnerUserID" });
			DropIndex("dbo.Article", new[] { "ParentArticleID" });
			DropIndex("dbo.Article", new[] { "SetID" });
			DropIndex("dbo.Article", new[] { "CategoryID" });
			DropIndex("dbo.ArticleCategory", new[] { "LastModifiedByUserID" });
			DropIndex("dbo.ArticleCategory", new[] { "CreatedByUserID" });
			DropIndex("dbo.ArticleCategory", new[] { "OwnerUserID" });
			DropIndex("dbo.AgencyBranch", new[] { "VicinityID" });
			DropIndex("dbo.AgencyBranch", new[] { "AgencyID" });
			DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "ReverseTransactionID" });
			DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "ForwardTransactionID" });
			DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "TargetUserID" });
			DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "SponsoredEntityID" });
			DropIndex("dbo.SponsoredEntityImpression", new[] { "BillingEntityID" });
			DropIndex("dbo.SponsoredEntityImpression", new[] { "HttpSessionID" });
			DropIndex("dbo.SponsoredEntityImpression", new[] { "ContentOwnerUserID" });
			DropIndex("dbo.SponsoredEntityImpression", new[] { "SponsoredEntityID" });
			DropIndex("dbo.SponsoredEntityClick", new[] { "BillingEntityID" });
			DropIndex("dbo.SponsoredEntityClick", new[] { "HttpSessionID" });
			DropIndex("dbo.SponsoredEntityClick", new[] { "ImpressionID" });
			DropIndex("dbo.SponsoredEntityClick", new[] { "SponsoredEntityID" });
			DropIndex("dbo.SponsoredEntityClickBilling", new[] { "ReverseTransactionID" });
			DropIndex("dbo.SponsoredEntityClickBilling", new[] { "ForwardTransactionID" });
			DropIndex("dbo.SponsoredEntityClickBilling", new[] { "TargetUserID" });
			DropIndex("dbo.SponsoredEntityClickBilling", new[] { "SponsoredEntityID" });
			DropIndex("dbo.SponsoredEntity", new[] { "BilledUserID" });
			DropIndex("dbo.SponsoredPropertyListing", new[] { "ListingID" });
			DropIndex("dbo.SponsoredPropertyListing", new[] { "SponsoredEntityID" });
			DropIndex("dbo.PropertyListingPhoto", new[] { "CreatorUserID" });
			DropIndex("dbo.PropertyListingPhoto", new[] { "CreatorSessionID" });
			DropIndex("dbo.PropertyListingPhoto", new[] { "PropertyListingID" });
			DropIndex("dbo.Unit", new[] { "BuildingID" });
			DropIndex("dbo.Vicinity", new[] { "ParentID" });
			DropIndex("dbo.CityRegion", new[] { "CityID" });
			DropIndex("dbo.Neighborhood", new[] { "CityID" });
			DropIndex("dbo.City", new[] { "ProvinceID" });
			DropIndex("dbo.Estate", new[] { "VicinityID" });
			DropIndex("dbo.Estate", new[] { "NeighborhoodID" });
			DropIndex("dbo.Estate", new[] { "CityRegionID" });
			DropIndex("dbo.Estate", new[] { "CityID" });
			DropIndex("dbo.Estate", new[] { "ProvinceID" });
			DropIndex("dbo.Building", new[] { "EstateID" });
			DropIndex("dbo.PropertyListing", new[] { "OwnerUserID" });
			DropIndex("dbo.PropertyListing", new[] { "CreatorUserID" });
			DropIndex("dbo.PropertyListing", new[] { "CreatorSessionID" });
			DropIndex("dbo.PropertyListing", new[] { "ContactInfoID" });
			DropIndex("dbo.PropertyListing", new[] { "RentConditionsID" });
			DropIndex("dbo.PropertyListing", new[] { "SaleConditionsID" });
			DropIndex("dbo.PropertyListing", new[] { "UnitID" });
			DropIndex("dbo.PropertyListing", new[] { "BuildingID" });
			DropIndex("dbo.PropertyListing", new[] { "EstateID" });
			DropIndex("dbo.PropertyListing", new[] { "VicinityID" });
			DropIndex("dbo.PropertyListing", new[] { "NeighborhoodID" });
			DropIndex("dbo.PropertyListing", new[] { "CityRegionID" });
			DropIndex("dbo.PropertyListing", new[] { "CityID" });
			DropIndex("dbo.PropertyListing", new[] { "ProvinceID" });
			DropIndex("dbo.UserFavoritePropertyListing", new[] { "ListingID" });
			DropIndex("dbo.UserFavoritePropertyListing", new[] { "UserID" });
			DropIndex("dbo.UserFavoritePropertyListing", new[] { "CreationSessionID" });
			DropIndex("dbo.ActivityLog", new[] { "ReviewedByID" });
			DropIndex("dbo.ActivityLog", new[] { "AuthenticatedUserID" });
			DropIndex("dbo.ActivityLog", new[] { "SessionID" });
			DropIndex("dbo.HttpSession", new[] { "UniqueVisitorID" });
			DropIndex("dbo.HttpSession", new[] { "UserID" });
			DropIndex("dbo.UserContactMethod", new[] { "UserID" });
			DropIndex("dbo.UserBillingTransaction", new[] { "UserID" });
			DropIndex("dbo.User", new[] { "CreatorSessionID" });
			DropIndex("dbo.AbuseFlag", new[] { "ApprovedByID" });
			DropIndex("dbo.AbuseFlag", new[] { "ReportedInSessionID" });
			DropIndex("dbo.AbuseFlag", new[] { "ReportedByID" });
			
			CreateIndex("dbo.AbuseFlag", "ReportedByID");
            CreateIndex("dbo.AbuseFlag", "ReportedInSessionID");
            CreateIndex("dbo.AbuseFlag", "ApprovedByID");
            CreateIndex("dbo.User", "CreatorSessionID");
            CreateIndex("dbo.UserBillingTransaction", "UserID");
            CreateIndex("dbo.UserContactMethod", "UserID");
            CreateIndex("dbo.HttpSession", "UserID");
            CreateIndex("dbo.HttpSession", "UniqueVisitorID");
            CreateIndex("dbo.ActivityLog", "SessionID");
            CreateIndex("dbo.ActivityLog", "AuthenticatedUserID");
            CreateIndex("dbo.ActivityLog", "ReviewedByID");
            CreateIndex("dbo.UserFavoritePropertyListing", "CreationSessionID");
            CreateIndex("dbo.UserFavoritePropertyListing", "UserID");
            CreateIndex("dbo.UserFavoritePropertyListing", "ListingID");
            CreateIndex("dbo.PropertyListing", "ProvinceID");
            CreateIndex("dbo.PropertyListing", "CityID");
            CreateIndex("dbo.PropertyListing", "CityRegionID");
            CreateIndex("dbo.PropertyListing", "NeighborhoodID");
            CreateIndex("dbo.PropertyListing", "VicinityID");
            CreateIndex("dbo.PropertyListing", "EstateID");
            CreateIndex("dbo.PropertyListing", "BuildingID");
            CreateIndex("dbo.PropertyListing", "UnitID");
            CreateIndex("dbo.PropertyListing", "SaleConditionsID");
            CreateIndex("dbo.PropertyListing", "RentConditionsID");
            CreateIndex("dbo.PropertyListing", "ContactInfoID");
            CreateIndex("dbo.PropertyListing", "CreatorSessionID");
            CreateIndex("dbo.PropertyListing", "CreatorUserID");
            CreateIndex("dbo.PropertyListing", "OwnerUserID");
            CreateIndex("dbo.Building", "EstateID");
            CreateIndex("dbo.Estate", "ProvinceID");
            CreateIndex("dbo.Estate", "CityID");
            CreateIndex("dbo.Estate", "CityRegionID");
            CreateIndex("dbo.Estate", "NeighborhoodID");
            CreateIndex("dbo.Estate", "VicinityID");
            CreateIndex("dbo.City", "ProvinceID");
            CreateIndex("dbo.Neighborhood", "CityID");
            CreateIndex("dbo.CityRegion", "CityID");
            CreateIndex("dbo.Vicinity", "ParentID");
            CreateIndex("dbo.Unit", "BuildingID");
            CreateIndex("dbo.PropertyListingPhoto", "PropertyListingID");
            CreateIndex("dbo.PropertyListingPhoto", "CreatorSessionID");
            CreateIndex("dbo.PropertyListingPhoto", "CreatorUserID");
            CreateIndex("dbo.SponsoredPropertyListing", "SponsoredEntityID");
            CreateIndex("dbo.SponsoredPropertyListing", "ListingID");
            CreateIndex("dbo.SponsoredEntity", "BilledUserID");
            CreateIndex("dbo.SponsoredEntityClickBilling", "SponsoredEntityID");
            CreateIndex("dbo.SponsoredEntityClickBilling", "TargetUserID");
            CreateIndex("dbo.SponsoredEntityClickBilling", "ForwardTransactionID");
            CreateIndex("dbo.SponsoredEntityClickBilling", "ReverseTransactionID");
            CreateIndex("dbo.SponsoredEntityClick", "SponsoredEntityID");
            CreateIndex("dbo.SponsoredEntityClick", "ImpressionID");
            CreateIndex("dbo.SponsoredEntityClick", "HttpSessionID");
            CreateIndex("dbo.SponsoredEntityClick", "BillingEntityID");
            CreateIndex("dbo.SponsoredEntityImpression", "SponsoredEntityID");
            CreateIndex("dbo.SponsoredEntityImpression", "ContentOwnerUserID");
            CreateIndex("dbo.SponsoredEntityImpression", "HttpSessionID");
            CreateIndex("dbo.SponsoredEntityImpression", "BillingEntityID");
            CreateIndex("dbo.SponsoredEntityImpressionBilling", "SponsoredEntityID");
            CreateIndex("dbo.SponsoredEntityImpressionBilling", "TargetUserID");
            CreateIndex("dbo.SponsoredEntityImpressionBilling", "ForwardTransactionID");
            CreateIndex("dbo.SponsoredEntityImpressionBilling", "ReverseTransactionID");
            CreateIndex("dbo.AgencyBranch", "AgencyID");
            CreateIndex("dbo.AgencyBranch", "VicinityID");
            CreateIndex("dbo.ArticleCategory", "OwnerUserID");
            CreateIndex("dbo.ArticleCategory", "CreatedByUserID");
            CreateIndex("dbo.ArticleCategory", "LastModifiedByUserID");
            CreateIndex("dbo.Article", "CategoryID");
            CreateIndex("dbo.Article", "SetID");
            CreateIndex("dbo.Article", "ParentArticleID");
            CreateIndex("dbo.Article", "OwnerUserID");
            CreateIndex("dbo.Article", "CreatedByUserID");
            CreateIndex("dbo.Article", "LastModifiedByUserID");
            CreateIndex("dbo.ArticleRevision", "ArticleID");
            CreateIndex("dbo.ArticleRevision", "CreatedByUserID");
            CreateIndex("dbo.ArticleRevision", "LastModifiedByUserID");
            CreateIndex("dbo.ArticleRevision", "FinalizedByUserID");
            CreateIndex("dbo.ArticleRevision", "PublishedByUserID");
            CreateIndex("dbo.ArticleSet", "CategoryID");
            CreateIndex("dbo.ArticleSet", "OwnerUserID");
            CreateIndex("dbo.ArticleSet", "CreatedByUserID");
            CreateIndex("dbo.ArticleSet", "LastModifiedByUserID");
            CreateIndex("dbo.LoginNameQuery", "SessionID");
            CreateIndex("dbo.LoginNameQuery", "TargetUserID");
            CreateIndex("dbo.LoginNameQuery", "ContactMethodID");
            CreateIndex("dbo.NotificationMessage", "TargetUserID");
            CreateIndex("dbo.OutgoingSmsMessage", "TargetUserID");
            CreateIndex("dbo.OutgoingSmsMessage", "NotificationID");
            CreateIndex("dbo.OutgoingSmsMessage", "RetryForMessageID");
            CreateIndex("dbo.PasswordResetRequest", "SessionID");
            CreateIndex("dbo.PasswordResetRequest", "TargetUserID");
            CreateIndex("dbo.PasswordResetRequest", "ContactMethodID");
            CreateIndex("dbo.PromotionalBonusCoupon", "CreatedByUserID");
            CreateIndex("dbo.PromotionalBonusCoupon", "TargetUserID");
            CreateIndex("dbo.PromotionalBonusCoupon", "ForwardTransactionID");
            CreateIndex("dbo.PromotionalBonusCoupon", "ReverseTransactionID");
            CreateIndex("dbo.PromotionalBonus", "CreatedByUserID");
            CreateIndex("dbo.PromotionalBonus", "TargetUserID");
            CreateIndex("dbo.PromotionalBonus", "ForwardTransactionID");
            CreateIndex("dbo.PromotionalBonus", "ReverseTransactionID");
            CreateIndex("dbo.PropertyListingPublishHistory", "PropertyListingID");
            CreateIndex("dbo.PropertyListingPublishHistory", "SessionID");
            CreateIndex("dbo.PropertyListingPublishHistory", "UserID");
            CreateIndex("dbo.PropertyListingUpdateHistory", "PropertyListingID");
            CreateIndex("dbo.PropertyListingUpdateHistory", "SessionID");
            CreateIndex("dbo.PropertyListingUpdateHistory", "UserID");
            CreateIndex("dbo.PropertyRequest", "CreatorSessionID");
            CreateIndex("dbo.PropertyRequest", "CreatorUserID");
            CreateIndex("dbo.PropertyRequest", "OwnerUserID");
            CreateIndex("dbo.PropertySearchHistory", "SessionID");
            CreateIndex("dbo.PropertySearchHistory", "UserID");
            CreateIndex("dbo.SavedPropertySearchEmailNotification", "PropertyListingID");
            CreateIndex("dbo.SavedPropertySearchEmailNotification", "SavedSearchID");
            CreateIndex("dbo.SavedPropertySearchEmailNotification", "ContactMethodID");
            CreateIndex("dbo.SavedPropertySearch", "UserID");
            CreateIndex("dbo.SavedPropertySearch", "CreatorSessionID");
            CreateIndex("dbo.SavedPropertySearch", "ProvinceID");
            CreateIndex("dbo.SavedPropertySearch", "CityID");
            CreateIndex("dbo.SavedPropertySearch", "CityRegionID");
            CreateIndex("dbo.SavedPropertySearch", "EmailNotificationTargetID");
            CreateIndex("dbo.SavedPropertySearch", "SmsNotificationTargetID");
            CreateIndex("dbo.SavedPropertySearchGeographicRegion", "PropertySearchID");
            CreateIndex("dbo.SavedPropertySearchGeographicRegion", "NeighborhoodID");
            CreateIndex("dbo.SavedPropertySearchGeographicRegion", "VicinityID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSms", "PropertyListingID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSms", "TargetUserID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSms", "ForwardTransactionID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSms", "ReverseTransactionID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "PropertyListingID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "PromotionalSmsID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "TargetUserID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "ForwardTransactionID");
            CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "ReverseTransactionID");
            CreateIndex("dbo.SavedPropertySearchSmsNotification", "PropertyListingID");
            CreateIndex("dbo.SavedPropertySearchSmsNotification", "SavedSearchID");
            CreateIndex("dbo.SavedPropertySearchSmsNotification", "ContactMethodID");
            CreateIndex("dbo.SavedPropertySearchSmsNotification", "TargetUserID");
            CreateIndex("dbo.SavedPropertySearchSmsNotification", "BillingID");
            CreateIndex("dbo.SavedSearchSmsNotificationBilling", "TargetUserID");
            CreateIndex("dbo.SavedSearchSmsNotificationBilling", "ForwardTransactionID");
            CreateIndex("dbo.SavedSearchSmsNotificationBilling", "ReverseTransactionID");
            CreateIndex("dbo.SavedPropertySearchUpdateHistory", "SavedSearchID");
            CreateIndex("dbo.SavedPropertySearchUpdateHistory", "SessionID");
            CreateIndex("dbo.SavedPropertySearchUpdateHistory", "UserID");
            CreateIndex("dbo.UserBalanceAdministrativeChange", "CreatedByUserID");
            CreateIndex("dbo.UserBalanceAdministrativeChange", "ReviewedByUserID");
            CreateIndex("dbo.UserBalanceAdministrativeChange", "TargetUserID");
            CreateIndex("dbo.UserBalanceAdministrativeChange", "ForwardTransactionID");
            CreateIndex("dbo.UserBalanceAdministrativeChange", "ReverseTransactionID");
            CreateIndex("dbo.UserContactMethodVerification", "SessionID");
            CreateIndex("dbo.UserContactMethodVerification", "TargetUserID");
            CreateIndex("dbo.UserContactMethodVerification", "TargetContactMethodID");
            CreateIndex("dbo.UserElectronicPayment", "ReviewedByUserID");
            CreateIndex("dbo.UserElectronicPayment", "TargetUserID");
            CreateIndex("dbo.UserElectronicPayment", "ForwardTransactionID");
            CreateIndex("dbo.UserElectronicPayment", "ReverseTransactionID");
            CreateIndex("dbo.UserRefundRequest", "ReviewedByUserID");
            CreateIndex("dbo.UserRefundRequest", "ClearedByUserID");
            CreateIndex("dbo.UserRefundRequest", "TargetUserID");
            CreateIndex("dbo.UserRefundRequest", "ForwardTransactionID");
            CreateIndex("dbo.UserRefundRequest", "ReverseTransactionID");
            CreateIndex("dbo.UserWireTransferPayment", "ReviewedByUserID");
            CreateIndex("dbo.UserWireTransferPayment", "TargetUserID");
            CreateIndex("dbo.UserWireTransferPayment", "ForwardTransactionID");
            CreateIndex("dbo.UserWireTransferPayment", "ReverseTransactionID");
            CreateIndex("dbo.CityAdjacencies", "BaseCityID");
            CreateIndex("dbo.CityAdjacencies", "AdjacentCityID");
            CreateIndex("dbo.NeighborhoodAdjacencies", "BaseNeighborhoodID");
            CreateIndex("dbo.NeighborhoodAdjacencies", "AdjacentNeighborhoodID");
            CreateIndex("dbo.CityRegionAdjacencies", "BaseCityRegionID");
            CreateIndex("dbo.CityRegionAdjacencies", "AdjacentCityRegionID");
            CreateIndex("dbo.CityRegionNeighborhoodRelation", "CityRegion_ID");
            CreateIndex("dbo.CityRegionNeighborhoodRelation", "Neighborhood_ID");
            CreateIndex("dbo.NeighborhoodSynonyms", "BaseNeighborhoodID");
            CreateIndex("dbo.NeighborhoodSynonyms", "SynonymNeighborhoodID");
            CreateIndex("dbo.ProvinceAdjacencies", "BaseProvinceID");
            CreateIndex("dbo.ProvinceAdjacencies", "AdjacentProvinceID");
        }
        
        public override void Down()
        {
            DropIndex("dbo.ProvinceAdjacencies", new[] { "AdjacentProvinceID" });
            DropIndex("dbo.ProvinceAdjacencies", new[] { "BaseProvinceID" });
            DropIndex("dbo.NeighborhoodSynonyms", new[] { "SynonymNeighborhoodID" });
            DropIndex("dbo.NeighborhoodSynonyms", new[] { "BaseNeighborhoodID" });
            DropIndex("dbo.CityRegionNeighborhoodRelation", new[] { "Neighborhood_ID" });
            DropIndex("dbo.CityRegionNeighborhoodRelation", new[] { "CityRegion_ID" });
            DropIndex("dbo.CityRegionAdjacencies", new[] { "AdjacentCityRegionID" });
            DropIndex("dbo.CityRegionAdjacencies", new[] { "BaseCityRegionID" });
            DropIndex("dbo.NeighborhoodAdjacencies", new[] { "AdjacentNeighborhoodID" });
            DropIndex("dbo.NeighborhoodAdjacencies", new[] { "BaseNeighborhoodID" });
            DropIndex("dbo.CityAdjacencies", new[] { "AdjacentCityID" });
            DropIndex("dbo.CityAdjacencies", new[] { "BaseCityID" });
            DropIndex("dbo.UserWireTransferPayment", new[] { "ReverseTransactionID" });
            DropIndex("dbo.UserWireTransferPayment", new[] { "ForwardTransactionID" });
            DropIndex("dbo.UserWireTransferPayment", new[] { "TargetUserID" });
            DropIndex("dbo.UserWireTransferPayment", new[] { "ReviewedByUserID" });
            DropIndex("dbo.UserRefundRequest", new[] { "ReverseTransactionID" });
            DropIndex("dbo.UserRefundRequest", new[] { "ForwardTransactionID" });
            DropIndex("dbo.UserRefundRequest", new[] { "TargetUserID" });
            DropIndex("dbo.UserRefundRequest", new[] { "ClearedByUserID" });
            DropIndex("dbo.UserRefundRequest", new[] { "ReviewedByUserID" });
            DropIndex("dbo.UserElectronicPayment", new[] { "ReverseTransactionID" });
            DropIndex("dbo.UserElectronicPayment", new[] { "ForwardTransactionID" });
            DropIndex("dbo.UserElectronicPayment", new[] { "TargetUserID" });
            DropIndex("dbo.UserElectronicPayment", new[] { "ReviewedByUserID" });
            DropIndex("dbo.UserContactMethodVerification", new[] { "TargetContactMethodID" });
            DropIndex("dbo.UserContactMethodVerification", new[] { "TargetUserID" });
            DropIndex("dbo.UserContactMethodVerification", new[] { "SessionID" });
            DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ReverseTransactionID" });
            DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ForwardTransactionID" });
            DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "TargetUserID" });
            DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "ReviewedByUserID" });
            DropIndex("dbo.UserBalanceAdministrativeChange", new[] { "CreatedByUserID" });
            DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "UserID" });
            DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "SessionID" });
            DropIndex("dbo.SavedPropertySearchUpdateHistory", new[] { "SavedSearchID" });
            DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "ReverseTransactionID" });
            DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "ForwardTransactionID" });
            DropIndex("dbo.SavedSearchSmsNotificationBilling", new[] { "TargetUserID" });
            DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "BillingID" });
            DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "TargetUserID" });
            DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "ContactMethodID" });
            DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "SavedSearchID" });
            DropIndex("dbo.SavedPropertySearchSmsNotification", new[] { "PropertyListingID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "ReverseTransactionID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "ForwardTransactionID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "TargetUserID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "PromotionalSmsID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", new[] { "PropertyListingID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "ReverseTransactionID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "ForwardTransactionID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "TargetUserID" });
            DropIndex("dbo.SavedPropertySearchPromotionalSms", new[] { "PropertyListingID" });
            DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "VicinityID" });
            DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "NeighborhoodID" });
            DropIndex("dbo.SavedPropertySearchGeographicRegion", new[] { "PropertySearchID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "SmsNotificationTargetID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "EmailNotificationTargetID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "CityRegionID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "CityID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "ProvinceID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "CreatorSessionID" });
            DropIndex("dbo.SavedPropertySearch", new[] { "UserID" });
            DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "ContactMethodID" });
            DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "SavedSearchID" });
            DropIndex("dbo.SavedPropertySearchEmailNotification", new[] { "PropertyListingID" });
            DropIndex("dbo.PropertySearchHistory", new[] { "UserID" });
            DropIndex("dbo.PropertySearchHistory", new[] { "SessionID" });
            DropIndex("dbo.PropertyRequest", new[] { "OwnerUserID" });
            DropIndex("dbo.PropertyRequest", new[] { "CreatorUserID" });
            DropIndex("dbo.PropertyRequest", new[] { "CreatorSessionID" });
            DropIndex("dbo.PropertyListingUpdateHistory", new[] { "UserID" });
            DropIndex("dbo.PropertyListingUpdateHistory", new[] { "SessionID" });
            DropIndex("dbo.PropertyListingUpdateHistory", new[] { "PropertyListingID" });
            DropIndex("dbo.PropertyListingPublishHistory", new[] { "UserID" });
            DropIndex("dbo.PropertyListingPublishHistory", new[] { "SessionID" });
            DropIndex("dbo.PropertyListingPublishHistory", new[] { "PropertyListingID" });
            DropIndex("dbo.PromotionalBonus", new[] { "ReverseTransactionID" });
            DropIndex("dbo.PromotionalBonus", new[] { "ForwardTransactionID" });
            DropIndex("dbo.PromotionalBonus", new[] { "TargetUserID" });
            DropIndex("dbo.PromotionalBonus", new[] { "CreatedByUserID" });
            DropIndex("dbo.PromotionalBonusCoupon", new[] { "ReverseTransactionID" });
            DropIndex("dbo.PromotionalBonusCoupon", new[] { "ForwardTransactionID" });
            DropIndex("dbo.PromotionalBonusCoupon", new[] { "TargetUserID" });
            DropIndex("dbo.PromotionalBonusCoupon", new[] { "CreatedByUserID" });
            DropIndex("dbo.PasswordResetRequest", new[] { "ContactMethodID" });
            DropIndex("dbo.PasswordResetRequest", new[] { "TargetUserID" });
            DropIndex("dbo.PasswordResetRequest", new[] { "SessionID" });
            DropIndex("dbo.OutgoingSmsMessage", new[] { "RetryForMessageID" });
            DropIndex("dbo.OutgoingSmsMessage", new[] { "NotificationID" });
            DropIndex("dbo.OutgoingSmsMessage", new[] { "TargetUserID" });
            DropIndex("dbo.NotificationMessage", new[] { "TargetUserID" });
            DropIndex("dbo.LoginNameQuery", new[] { "ContactMethodID" });
            DropIndex("dbo.LoginNameQuery", new[] { "TargetUserID" });
            DropIndex("dbo.LoginNameQuery", new[] { "SessionID" });
            DropIndex("dbo.ArticleSet", new[] { "LastModifiedByUserID" });
            DropIndex("dbo.ArticleSet", new[] { "CreatedByUserID" });
            DropIndex("dbo.ArticleSet", new[] { "OwnerUserID" });
            DropIndex("dbo.ArticleSet", new[] { "CategoryID" });
            DropIndex("dbo.ArticleRevision", new[] { "PublishedByUserID" });
            DropIndex("dbo.ArticleRevision", new[] { "FinalizedByUserID" });
            DropIndex("dbo.ArticleRevision", new[] { "LastModifiedByUserID" });
            DropIndex("dbo.ArticleRevision", new[] { "CreatedByUserID" });
            DropIndex("dbo.ArticleRevision", new[] { "ArticleID" });
            DropIndex("dbo.Article", new[] { "LastModifiedByUserID" });
            DropIndex("dbo.Article", new[] { "CreatedByUserID" });
            DropIndex("dbo.Article", new[] { "OwnerUserID" });
            DropIndex("dbo.Article", new[] { "ParentArticleID" });
            DropIndex("dbo.Article", new[] { "SetID" });
            DropIndex("dbo.Article", new[] { "CategoryID" });
            DropIndex("dbo.ArticleCategory", new[] { "LastModifiedByUserID" });
            DropIndex("dbo.ArticleCategory", new[] { "CreatedByUserID" });
            DropIndex("dbo.ArticleCategory", new[] { "OwnerUserID" });
            DropIndex("dbo.AgencyBranch", new[] { "VicinityID" });
            DropIndex("dbo.AgencyBranch", new[] { "AgencyID" });
            DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "ReverseTransactionID" });
            DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "ForwardTransactionID" });
            DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "TargetUserID" });
            DropIndex("dbo.SponsoredEntityImpressionBilling", new[] { "SponsoredEntityID" });
            DropIndex("dbo.SponsoredEntityImpression", new[] { "BillingEntityID" });
            DropIndex("dbo.SponsoredEntityImpression", new[] { "HttpSessionID" });
            DropIndex("dbo.SponsoredEntityImpression", new[] { "ContentOwnerUserID" });
            DropIndex("dbo.SponsoredEntityImpression", new[] { "SponsoredEntityID" });
            DropIndex("dbo.SponsoredEntityClick", new[] { "BillingEntityID" });
            DropIndex("dbo.SponsoredEntityClick", new[] { "HttpSessionID" });
            DropIndex("dbo.SponsoredEntityClick", new[] { "ImpressionID" });
            DropIndex("dbo.SponsoredEntityClick", new[] { "SponsoredEntityID" });
            DropIndex("dbo.SponsoredEntityClickBilling", new[] { "ReverseTransactionID" });
            DropIndex("dbo.SponsoredEntityClickBilling", new[] { "ForwardTransactionID" });
            DropIndex("dbo.SponsoredEntityClickBilling", new[] { "TargetUserID" });
            DropIndex("dbo.SponsoredEntityClickBilling", new[] { "SponsoredEntityID" });
            DropIndex("dbo.SponsoredEntity", new[] { "BilledUserID" });
            DropIndex("dbo.SponsoredPropertyListing", new[] { "ListingID" });
            DropIndex("dbo.SponsoredPropertyListing", new[] { "SponsoredEntityID" });
            DropIndex("dbo.PropertyListingPhoto", new[] { "CreatorUserID" });
            DropIndex("dbo.PropertyListingPhoto", new[] { "CreatorSessionID" });
            DropIndex("dbo.PropertyListingPhoto", new[] { "PropertyListingID" });
            DropIndex("dbo.Unit", new[] { "BuildingID" });
            DropIndex("dbo.Vicinity", new[] { "ParentID" });
            DropIndex("dbo.CityRegion", new[] { "CityID" });
            DropIndex("dbo.Neighborhood", new[] { "CityID" });
            DropIndex("dbo.City", new[] { "ProvinceID" });
            DropIndex("dbo.Estate", new[] { "VicinityID" });
            DropIndex("dbo.Estate", new[] { "NeighborhoodID" });
            DropIndex("dbo.Estate", new[] { "CityRegionID" });
            DropIndex("dbo.Estate", new[] { "CityID" });
            DropIndex("dbo.Estate", new[] { "ProvinceID" });
            DropIndex("dbo.Building", new[] { "EstateID" });
            DropIndex("dbo.PropertyListing", new[] { "OwnerUserID" });
            DropIndex("dbo.PropertyListing", new[] { "CreatorUserID" });
            DropIndex("dbo.PropertyListing", new[] { "CreatorSessionID" });
            DropIndex("dbo.PropertyListing", new[] { "ContactInfoID" });
            DropIndex("dbo.PropertyListing", new[] { "RentConditionsID" });
            DropIndex("dbo.PropertyListing", new[] { "SaleConditionsID" });
            DropIndex("dbo.PropertyListing", new[] { "UnitID" });
            DropIndex("dbo.PropertyListing", new[] { "BuildingID" });
            DropIndex("dbo.PropertyListing", new[] { "EstateID" });
            DropIndex("dbo.PropertyListing", new[] { "VicinityID" });
            DropIndex("dbo.PropertyListing", new[] { "NeighborhoodID" });
            DropIndex("dbo.PropertyListing", new[] { "CityRegionID" });
            DropIndex("dbo.PropertyListing", new[] { "CityID" });
            DropIndex("dbo.PropertyListing", new[] { "ProvinceID" });
            DropIndex("dbo.UserFavoritePropertyListing", new[] { "ListingID" });
            DropIndex("dbo.UserFavoritePropertyListing", new[] { "UserID" });
            DropIndex("dbo.UserFavoritePropertyListing", new[] { "CreationSessionID" });
            DropIndex("dbo.ActivityLog", new[] { "ReviewedByID" });
            DropIndex("dbo.ActivityLog", new[] { "AuthenticatedUserID" });
            DropIndex("dbo.ActivityLog", new[] { "SessionID" });
            DropIndex("dbo.HttpSession", new[] { "UniqueVisitorID" });
            DropIndex("dbo.HttpSession", new[] { "UserID" });
            DropIndex("dbo.UserContactMethod", new[] { "UserID" });
            DropIndex("dbo.UserBillingTransaction", new[] { "UserID" });
            DropIndex("dbo.User", new[] { "CreatorSessionID" });
            DropIndex("dbo.AbuseFlag", new[] { "ApprovedByID" });
            DropIndex("dbo.AbuseFlag", new[] { "ReportedInSessionID" });
            DropIndex("dbo.AbuseFlag", new[] { "ReportedByID" });

			CreateIndex("dbo.AbuseFlag", "ReportedByID");
			CreateIndex("dbo.AbuseFlag", "ReportedInSessionID");
			CreateIndex("dbo.AbuseFlag", "ApprovedByID");
			CreateIndex("dbo.User", "CreatorSessionID");
			CreateIndex("dbo.UserBillingTransaction", "UserID");
			CreateIndex("dbo.UserContactMethod", "UserID");
			CreateIndex("dbo.HttpSession", "UserID");
			CreateIndex("dbo.HttpSession", "UniqueVisitorID");
			CreateIndex("dbo.ActivityLog", "SessionID");
			CreateIndex("dbo.ActivityLog", "AuthenticatedUserID");
			CreateIndex("dbo.ActivityLog", "ReviewedByID");
			CreateIndex("dbo.UserFavoritePropertyListing", "CreationSessionID");
			CreateIndex("dbo.UserFavoritePropertyListing", "UserID");
			CreateIndex("dbo.UserFavoritePropertyListing", "ListingID");
			CreateIndex("dbo.PropertyListing", "ProvinceID");
			CreateIndex("dbo.PropertyListing", "CityID");
			CreateIndex("dbo.PropertyListing", "CityRegionID");
			CreateIndex("dbo.PropertyListing", "NeighborhoodID");
			CreateIndex("dbo.PropertyListing", "VicinityID");
			CreateIndex("dbo.PropertyListing", "EstateID");
			CreateIndex("dbo.PropertyListing", "BuildingID");
			CreateIndex("dbo.PropertyListing", "UnitID");
			CreateIndex("dbo.PropertyListing", "SaleConditionsID");
			CreateIndex("dbo.PropertyListing", "RentConditionsID");
			CreateIndex("dbo.PropertyListing", "ContactInfoID");
			CreateIndex("dbo.PropertyListing", "CreatorSessionID");
			CreateIndex("dbo.PropertyListing", "CreatorUserID");
			CreateIndex("dbo.PropertyListing", "OwnerUserID");
			CreateIndex("dbo.Building", "EstateID");
			CreateIndex("dbo.Estate", "ProvinceID");
			CreateIndex("dbo.Estate", "CityID");
			CreateIndex("dbo.Estate", "CityRegionID");
			CreateIndex("dbo.Estate", "NeighborhoodID");
			CreateIndex("dbo.Estate", "VicinityID");
			CreateIndex("dbo.City", "ProvinceID");
			CreateIndex("dbo.Neighborhood", "CityID");
			CreateIndex("dbo.CityRegion", "CityID");
			CreateIndex("dbo.Vicinity", "ParentID");
			CreateIndex("dbo.Unit", "BuildingID");
			CreateIndex("dbo.PropertyListingPhoto", "PropertyListingID");
			CreateIndex("dbo.PropertyListingPhoto", "CreatorSessionID");
			CreateIndex("dbo.PropertyListingPhoto", "CreatorUserID");
			CreateIndex("dbo.SponsoredPropertyListing", "SponsoredEntityID");
			CreateIndex("dbo.SponsoredPropertyListing", "ListingID");
			CreateIndex("dbo.SponsoredEntity", "BilledUserID");
			CreateIndex("dbo.SponsoredEntityClickBilling", "SponsoredEntityID");
			CreateIndex("dbo.SponsoredEntityClickBilling", "TargetUserID");
			CreateIndex("dbo.SponsoredEntityClickBilling", "ForwardTransactionID");
			CreateIndex("dbo.SponsoredEntityClickBilling", "ReverseTransactionID");
			CreateIndex("dbo.SponsoredEntityClick", "SponsoredEntityID");
			CreateIndex("dbo.SponsoredEntityClick", "ImpressionID");
			CreateIndex("dbo.SponsoredEntityClick", "HttpSessionID");
			CreateIndex("dbo.SponsoredEntityClick", "BillingEntityID");
			CreateIndex("dbo.SponsoredEntityImpression", "SponsoredEntityID");
			CreateIndex("dbo.SponsoredEntityImpression", "ContentOwnerUserID");
			CreateIndex("dbo.SponsoredEntityImpression", "HttpSessionID");
			CreateIndex("dbo.SponsoredEntityImpression", "BillingEntityID");
			CreateIndex("dbo.SponsoredEntityImpressionBilling", "SponsoredEntityID");
			CreateIndex("dbo.SponsoredEntityImpressionBilling", "TargetUserID");
			CreateIndex("dbo.SponsoredEntityImpressionBilling", "ForwardTransactionID");
			CreateIndex("dbo.SponsoredEntityImpressionBilling", "ReverseTransactionID");
			CreateIndex("dbo.AgencyBranch", "AgencyID");
			CreateIndex("dbo.AgencyBranch", "VicinityID");
			CreateIndex("dbo.ArticleCategory", "OwnerUserID");
			CreateIndex("dbo.ArticleCategory", "CreatedByUserID");
			CreateIndex("dbo.ArticleCategory", "LastModifiedByUserID");
			CreateIndex("dbo.Article", "CategoryID");
			CreateIndex("dbo.Article", "SetID");
			CreateIndex("dbo.Article", "ParentArticleID");
			CreateIndex("dbo.Article", "OwnerUserID");
			CreateIndex("dbo.Article", "CreatedByUserID");
			CreateIndex("dbo.Article", "LastModifiedByUserID");
			CreateIndex("dbo.ArticleRevision", "ArticleID");
			CreateIndex("dbo.ArticleRevision", "CreatedByUserID");
			CreateIndex("dbo.ArticleRevision", "LastModifiedByUserID");
			CreateIndex("dbo.ArticleRevision", "FinalizedByUserID");
			CreateIndex("dbo.ArticleRevision", "PublishedByUserID");
			CreateIndex("dbo.ArticleSet", "CategoryID");
			CreateIndex("dbo.ArticleSet", "OwnerUserID");
			CreateIndex("dbo.ArticleSet", "CreatedByUserID");
			CreateIndex("dbo.ArticleSet", "LastModifiedByUserID");
			CreateIndex("dbo.LoginNameQuery", "SessionID");
			CreateIndex("dbo.LoginNameQuery", "TargetUserID");
			CreateIndex("dbo.LoginNameQuery", "ContactMethodID");
			CreateIndex("dbo.NotificationMessage", "TargetUserID");
			CreateIndex("dbo.OutgoingSmsMessage", "TargetUserID");
			CreateIndex("dbo.OutgoingSmsMessage", "NotificationID");
			CreateIndex("dbo.OutgoingSmsMessage", "RetryForMessageID");
			CreateIndex("dbo.PasswordResetRequest", "SessionID");
			CreateIndex("dbo.PasswordResetRequest", "TargetUserID");
			CreateIndex("dbo.PasswordResetRequest", "ContactMethodID");
			CreateIndex("dbo.PromotionalBonusCoupon", "CreatedByUserID");
			CreateIndex("dbo.PromotionalBonusCoupon", "TargetUserID");
			CreateIndex("dbo.PromotionalBonusCoupon", "ForwardTransactionID");
			CreateIndex("dbo.PromotionalBonusCoupon", "ReverseTransactionID");
			CreateIndex("dbo.PromotionalBonus", "CreatedByUserID");
			CreateIndex("dbo.PromotionalBonus", "TargetUserID");
			CreateIndex("dbo.PromotionalBonus", "ForwardTransactionID");
			CreateIndex("dbo.PromotionalBonus", "ReverseTransactionID");
			CreateIndex("dbo.PropertyListingPublishHistory", "PropertyListingID");
			CreateIndex("dbo.PropertyListingPublishHistory", "SessionID");
			CreateIndex("dbo.PropertyListingPublishHistory", "UserID");
			CreateIndex("dbo.PropertyListingUpdateHistory", "PropertyListingID");
			CreateIndex("dbo.PropertyListingUpdateHistory", "SessionID");
			CreateIndex("dbo.PropertyListingUpdateHistory", "UserID");
			CreateIndex("dbo.PropertyRequest", "CreatorSessionID");
			CreateIndex("dbo.PropertyRequest", "CreatorUserID");
			CreateIndex("dbo.PropertyRequest", "OwnerUserID");
			CreateIndex("dbo.PropertySearchHistory", "SessionID");
			CreateIndex("dbo.PropertySearchHistory", "UserID");
			CreateIndex("dbo.SavedPropertySearchEmailNotification", "PropertyListingID");
			CreateIndex("dbo.SavedPropertySearchEmailNotification", "SavedSearchID");
			CreateIndex("dbo.SavedPropertySearchEmailNotification", "ContactMethodID");
			CreateIndex("dbo.SavedPropertySearch", "UserID");
			CreateIndex("dbo.SavedPropertySearch", "CreatorSessionID");
			CreateIndex("dbo.SavedPropertySearch", "ProvinceID");
			CreateIndex("dbo.SavedPropertySearch", "CityID");
			CreateIndex("dbo.SavedPropertySearch", "CityRegionID");
			CreateIndex("dbo.SavedPropertySearch", "EmailNotificationTargetID");
			CreateIndex("dbo.SavedPropertySearch", "SmsNotificationTargetID");
			CreateIndex("dbo.SavedPropertySearchGeographicRegion", "PropertySearchID");
			CreateIndex("dbo.SavedPropertySearchGeographicRegion", "NeighborhoodID");
			CreateIndex("dbo.SavedPropertySearchGeographicRegion", "VicinityID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSms", "PropertyListingID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSms", "TargetUserID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSms", "ForwardTransactionID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSms", "ReverseTransactionID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "PropertyListingID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "PromotionalSmsID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "TargetUserID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "ForwardTransactionID");
			CreateIndex("dbo.SavedPropertySearchPromotionalSmsNotDeliveredReturn", "ReverseTransactionID");
			CreateIndex("dbo.SavedPropertySearchSmsNotification", "PropertyListingID");
			CreateIndex("dbo.SavedPropertySearchSmsNotification", "SavedSearchID");
			CreateIndex("dbo.SavedPropertySearchSmsNotification", "ContactMethodID");
			CreateIndex("dbo.SavedPropertySearchSmsNotification", "TargetUserID");
			CreateIndex("dbo.SavedPropertySearchSmsNotification", "BillingID");
			CreateIndex("dbo.SavedSearchSmsNotificationBilling", "TargetUserID");
			CreateIndex("dbo.SavedSearchSmsNotificationBilling", "ForwardTransactionID");
			CreateIndex("dbo.SavedSearchSmsNotificationBilling", "ReverseTransactionID");
			CreateIndex("dbo.SavedPropertySearchUpdateHistory", "SavedSearchID");
			CreateIndex("dbo.SavedPropertySearchUpdateHistory", "SessionID");
			CreateIndex("dbo.SavedPropertySearchUpdateHistory", "UserID");
			CreateIndex("dbo.UserBalanceAdministrativeChange", "CreatedByUserID");
			CreateIndex("dbo.UserBalanceAdministrativeChange", "ReviewedByUserID");
			CreateIndex("dbo.UserBalanceAdministrativeChange", "TargetUserID");
			CreateIndex("dbo.UserBalanceAdministrativeChange", "ForwardTransactionID");
			CreateIndex("dbo.UserBalanceAdministrativeChange", "ReverseTransactionID");
			CreateIndex("dbo.UserContactMethodVerification", "SessionID");
			CreateIndex("dbo.UserContactMethodVerification", "TargetUserID");
			CreateIndex("dbo.UserContactMethodVerification", "TargetContactMethodID");
			CreateIndex("dbo.UserElectronicPayment", "ReviewedByUserID");
			CreateIndex("dbo.UserElectronicPayment", "TargetUserID");
			CreateIndex("dbo.UserElectronicPayment", "ForwardTransactionID");
			CreateIndex("dbo.UserElectronicPayment", "ReverseTransactionID");
			CreateIndex("dbo.UserRefundRequest", "ReviewedByUserID");
			CreateIndex("dbo.UserRefundRequest", "ClearedByUserID");
			CreateIndex("dbo.UserRefundRequest", "TargetUserID");
			CreateIndex("dbo.UserRefundRequest", "ForwardTransactionID");
			CreateIndex("dbo.UserRefundRequest", "ReverseTransactionID");
			CreateIndex("dbo.UserWireTransferPayment", "ReviewedByUserID");
			CreateIndex("dbo.UserWireTransferPayment", "TargetUserID");
			CreateIndex("dbo.UserWireTransferPayment", "ForwardTransactionID");
			CreateIndex("dbo.UserWireTransferPayment", "ReverseTransactionID");
			CreateIndex("dbo.CityAdjacencies", "BaseCityID");
			CreateIndex("dbo.CityAdjacencies", "AdjacentCityID");
			CreateIndex("dbo.NeighborhoodAdjacencies", "BaseNeighborhoodID");
			CreateIndex("dbo.NeighborhoodAdjacencies", "AdjacentNeighborhoodID");
			CreateIndex("dbo.CityRegionAdjacencies", "BaseCityRegionID");
			CreateIndex("dbo.CityRegionAdjacencies", "AdjacentCityRegionID");
			CreateIndex("dbo.CityRegionNeighborhoodRelation", "CityRegion_ID");
			CreateIndex("dbo.CityRegionNeighborhoodRelation", "Neighborhood_ID");
			CreateIndex("dbo.NeighborhoodSynonyms", "BaseNeighborhoodID");
			CreateIndex("dbo.NeighborhoodSynonyms", "SynonymNeighborhoodID");
			CreateIndex("dbo.ProvinceAdjacencies", "BaseProvinceID");
			CreateIndex("dbo.ProvinceAdjacencies", "AdjacentProvinceID");
        }
    }
}
