// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _158AgencyContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_158AgencyContent));
        
        string IMigrationMetadata.Id
        {
            get { return "201410131152057_1.5.8.AgencyContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
