// <auto-generated />
namespace JahanJooy.RealEstate.Core.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _144 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_144));
        
        string IMigrationMetadata.Id
        {
            get { return "201405190541040_1.4.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
