//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Areas.Ad.Models.SponsoredProperty {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SponsoredPropertyModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SponsoredPropertyModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Areas.Ad.Models.SponsoredProperty.SponsoredPropertyModel" +
                            "Resources", typeof(SponsoredPropertyModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج ماه.
        /// </summary>
        public static string DaysBeforeExpirationOption_FiveMonths {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_FiveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار روز.
        /// </summary>
        public static string DaysBeforeExpirationOption_FourDays {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_FourDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار ماه.
        /// </summary>
        public static string DaysBeforeExpirationOption_FourMonths {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_FourMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ماه.
        /// </summary>
        public static string DaysBeforeExpirationOption_OneMonth {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک هفته.
        /// </summary>
        public static string DaysBeforeExpirationOption_OneWeek {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه ماه.
        /// </summary>
        public static string DaysBeforeExpirationOption_ThreeMonths {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه هفته.
        /// </summary>
        public static string DaysBeforeExpirationOption_ThreeWeeks {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_ThreeWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو روز.
        /// </summary>
        public static string DaysBeforeExpirationOption_TwoDays {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو ماه.
        /// </summary>
        public static string DaysBeforeExpirationOption_TwoMonths {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو هفته.
        /// </summary>
        public static string DaysBeforeExpirationOption_TwoWeeks {
            get {
                return ResourceManager.GetString("DaysBeforeExpirationOption_TwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش محاسبه هزینه.
        /// </summary>
        public static string Label_BillingMethod {
            get {
                return ResourceManager.GetString("Label_BillingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن اختیاری.
        /// </summary>
        public static string Label_CustomCaption {
            get {
                return ResourceManager.GetString("Label_CustomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان نمایش ویژه.
        /// </summary>
        public static string Label_DaysBeforeExpire {
            get {
                return ResourceManager.GetString("Label_DaysBeforeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در جستجوهایی که مطابق مشخصات ملک نیستند.
        /// </summary>
        public static string Label_IgnoreSearchQuery {
            get {
                return ResourceManager.GetString("Label_IgnoreSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر پرداخت برای هر کلیک.
        /// </summary>
        public static string Label_MaxPayPerClick {
            get {
                return ResourceManager.GetString("Label_MaxPayPerClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر پرداخت برای هر نمایش.
        /// </summary>
        public static string Label_MaxPayPerImpression {
            get {
                return ResourceManager.GetString("Label_MaxPayPerImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صفحات دوم به بعد هم نمایش داده شود.
        /// </summary>
        public static string Label_ShowInAllPages {
            get {
                return ResourceManager.GetString("Label_ShowInAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روی نقشه هم به صورت ویژه نمایش داده شود.
        /// </summary>
        public static string Label_ShowOnMap {
            get {
                return ResourceManager.GetString("Label_ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_CustomCaption_Length {
            get {
                return ResourceManager.GetString("Validation_CustomCaption_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_MaxPayPerClick_Numeric {
            get {
                return ResourceManager.GetString("Validation_MaxPayPerClick_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_MaxPayPerClick_Range {
            get {
                return ResourceManager.GetString("Validation_MaxPayPerClick_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید عددی باشد.
        /// </summary>
        public static string Validation_MaxPayPerImpression_Numeric {
            get {
                return ResourceManager.GetString("Validation_MaxPayPerImpression_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_MaxPayPerImpression_Range {
            get {
                return ResourceManager.GetString("Validation_MaxPayPerImpression_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یک متن برای عنوان وارد کنید.
        /// </summary>
        public static string Validation_Title_Required {
            get {
                return ResourceManager.GetString("Validation_Title_Required", resourceCulture);
            }
        }
    }
}
