//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Areas.Ad.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SponsoredPropertyControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SponsoredPropertyControllerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Areas.Ad.Controllers.SponsoredPropertyControllerResource" +
                            "s", typeof(SponsoredPropertyControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع از روش پرداخت قابل قبول نیست.
        /// </summary>
        internal static string BillingMethod_UnsupportedPaymentMethod {
            get {
                return ResourceManager.GetString("BillingMethod_UnsupportedPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ مشخص شده برای حداکثر پرداخت برای هر کلیک، کمتر از حداقل قابل پرداخت است..
        /// </summary>
        internal static string MaxPayPerClick_SpecifiedMaxPayPerClickLessThanMinimum {
            get {
                return ResourceManager.GetString("MaxPayPerClick_SpecifiedMaxPayPerClickLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ مشخص شده برای حداکثر پرداخت برای هر نمایش، کمتر از حداقل قابل پرداخت است..
        /// </summary>
        internal static string MaxPayPerImpression_SpecifiedMaxPayPerImpressionLessThanMinimum {
            get {
                return ResourceManager.GetString("MaxPayPerImpression_SpecifiedMaxPayPerImpressionLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی ویژه برای ملک کد {0}.
        /// </summary>
        internal static string NewSponsorship_DefaultTitleFormat {
            get {
                return ResourceManager.GetString("NewSponsorship_DefaultTitleFormat", resourceCulture);
            }
        }
    }
}
