//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Models.PropertyRequest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyRequestEditModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyRequestEditModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Models.PropertyRequest.PropertyRequestEditModelResources" +
                            "", typeof(PropertyRequestEditModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات آدرس (در صورت نیاز).
        /// </summary>
        public static string Label_AdditionalAddressInfo {
            get {
                return ResourceManager.GetString("Label_AdditionalAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیگر ویژگی های ملک.
        /// </summary>
        public static string Label_AdditionalSpecialFeatures {
            get {
                return ResourceManager.GetString("Label_AdditionalSpecialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس آژانس املاک.
        /// </summary>
        public static string Label_AgencyAddress {
            get {
                return ResourceManager.GetString("Label_AgencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آگهی را واسطه ثبت می کند؟.
        /// </summary>
        public static string Label_AgencyListing {
            get {
                return ResourceManager.GetString("Label_AgencyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با مشاورین دیگر همکاری میکنید؟.
        /// </summary>
        public static string Label_AgencyListing_OtherAgencyPermitted {
            get {
                return ResourceManager.GetString("Label_AgencyListing_OtherAgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام آژانس.
        /// </summary>
        public static string Label_AgencyName {
            get {
                return ResourceManager.GetString("Label_AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمر ساختمان.
        /// </summary>
        public static string Label_BuildingAgeYears {
            get {
                return ResourceManager.GetString("Label_BuildingAgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Label_ContactEmail {
            get {
                return ResourceManager.GetString("Label_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Label_ContactName {
            get {
                return ResourceManager.GetString("Label_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Label_ContactPhone1 {
            get {
                return ResourceManager.GetString("Label_ContactPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن دو.
        /// </summary>
        public static string Label_ContactPhone2 {
            get {
                return ResourceManager.GetString("Label_ContactPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت زمین .
        /// </summary>
        public static string Label_EstateArea {
            get {
                return ResourceManager.GetString("Label_EstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت زمین تا.
        /// </summary>
        public static string Label_EstateAreaMaximum {
            get {
                return ResourceManager.GetString("Label_EstateAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت زمین از.
        /// </summary>
        public static string Label_EstateAreaMinimum {
            get {
                return ResourceManager.GetString("Label_EstateAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت زمین.
        /// </summary>
        public static string Label_EstateDirection {
            get {
                return ResourceManager.GetString("Label_EstateDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند زمین.
        /// </summary>
        public static string Label_EstateVoucherType {
            get {
                return ResourceManager.GetString("Label_EstateVoucherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشش.
        /// </summary>
        public static string Label_FaceType {
            get {
                return ResourceManager.GetString("Label_FaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درب برقی پارکینگ.
        /// </summary>
        public static string Label_HasAutomaticParkingDoor {
            get {
                return ResourceManager.GetString("Label_HasAutomaticParkingDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازسازی شده.
        /// </summary>
        public static string Label_HasBeenReconstructed {
            get {
                return ResourceManager.GetString("Label_HasBeenReconstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسانسور دارد.
        /// </summary>
        public static string Label_HasElevator {
            get {
                return ResourceManager.GetString("Label_HasElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستشویی فرنگی دارد.
        /// </summary>
        public static string Label_HasForeignLavatory {
            get {
                return ResourceManager.GetString("Label_HasForeignLavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن اجتماعات دارد.
        /// </summary>
        public static string Label_HasGatheringHall {
            get {
                return ResourceManager.GetString("Label_HasGatheringHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستشویی ایرانی دارد.
        /// </summary>
        public static string Label_HasIranianLavatory {
            get {
                return ResourceManager.GetString("Label_HasIranianLavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جکوزی دارد.
        /// </summary>
        public static string Label_HasJacuzzi {
            get {
                return ResourceManager.GetString("Label_HasJacuzzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسیو در اخیتار دارد.
        /// </summary>
        public static string Label_HasPrivatePatio {
            get {
                return ResourceManager.GetString("Label_HasPrivatePatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سونا دارد.
        /// </summary>
        public static string Label_HasSauna {
            get {
                return ResourceManager.GetString("Label_HasSauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخر دارد.
        /// </summary>
        public static string Label_HasSwimmingPool {
            get {
                return ResourceManager.GetString("Label_HasSwimmingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وام قابل انتقال دارد.
        /// </summary>
        public static string Label_HasTransferableLoan {
            get {
                return ResourceManager.GetString("Label_HasTransferableLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیفون تصویری دارد.
        /// </summary>
        public static string Label_HasVideoEyePhone {
            get {
                return ResourceManager.GetString("Label_HasVideoEyePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای.
        /// </summary>
        public static string Label_IntentionOfRequester {
            get {
                return ResourceManager.GetString("Label_IntentionOfRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوبلکس است.
        /// </summary>
        public static string Label_IsDuplex {
            get {
                return ResourceManager.GetString("Label_IsDuplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس بدنه کابینت ها.
        /// </summary>
        public static string Label_KitchenCabinetBodyType {
            get {
                return ResourceManager.GetString("Label_KitchenCabinetBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس رویه کابینت ها.
        /// </summary>
        public static string Label_KitchenCabinetTopType {
            get {
                return ResourceManager.GetString("Label_KitchenCabinetTopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس کف پذیرایی.
        /// </summary>
        public static string Label_LivingRoomFloor {
            get {
                return ResourceManager.GetString("Label_LivingRoomFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نور اصلی واحد از سمت.
        /// </summary>
        public static string Label_MainDaylightDirection {
            get {
                return ResourceManager.GetString("Label_MainDaylightDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن از چقدر کمتر نباشد.
        /// </summary>
        public static string Label_MinimumMortgage {
            get {
                return ResourceManager.GetString("Label_MinimumMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره از چقدر کمتر نباشد.
        /// </summary>
        public static string Label_MinimumRent {
            get {
                return ResourceManager.GetString("Label_MinimumRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن.
        /// </summary>
        public static string Label_Mortgage {
            get {
                return ResourceManager.GetString("Label_Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن و اجاره قابل تبدیل است؟.
        /// </summary>
        public static string Label_MortgageAndRentConvertible {
            get {
                return ResourceManager.GetString("Label_MortgageAndRentConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مشاورین می توانند با شما تماس بگیرند؟.
        /// </summary>
        public static string Label_NoAgencyListing_AgencyPermitted {
            get {
                return ResourceManager.GetString("Label_NoAgencyListing_AgencyPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند طبقه روی همکف دارد.
        /// </summary>
        public static string Label_NumberFloorsAboveGround {
            get {
                return ResourceManager.GetString("Label_NumberFloorsAboveGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مستر بدروم ها.
        /// </summary>
        public static string Label_NumberOfMasterBedrooms {
            get {
                return ResourceManager.GetString("Label_NumberOfMasterBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد پارکینگ ها.
        /// </summary>
        public static string Label_NumberOfParkings {
            get {
                return ResourceManager.GetString("Label_NumberOfParkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد خواب.
        /// </summary>
        public static string Label_NumberOfRooms {
            get {
                return ResourceManager.GetString("Label_NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند واحد در طبقه دارد.
        /// </summary>
        public static string Label_NumberOfUnitsPerFloor {
            get {
                return ResourceManager.GetString("Label_NumberOfUnitsPerFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول بَر به گذر اصلی.
        /// </summary>
        public static string Label_PassageEdgeLength {
            get {
                return ResourceManager.GetString("Label_PassageEdgeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر مترمربع زمین.
        /// </summary>
        public static string Label_PricePerEstateArea {
            get {
                return ResourceManager.GetString("Label_PricePerEstateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر مربع آپارتمان.
        /// </summary>
        public static string Label_PricePerUnitArea {
            get {
                return ResourceManager.GetString("Label_PricePerUnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیوه مشخص کردن قیمت.
        /// </summary>
        public static string Label_PriceSpecificationType {
            get {
                return ResourceManager.GetString("Label_PriceSpecificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک درخواستی.
        /// </summary>
        public static string Label_PropertyType {
            get {
                return ResourceManager.GetString("Label_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان عمومی بودن آگهی روی اینترنت.
        /// </summary>
        public static string Label_PublishDuration {
            get {
                return ResourceManager.GetString("Label_PublishDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره.
        /// </summary>
        public static string Label_Rent {
            get {
                return ResourceManager.GetString("Label_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت انباری.
        /// </summary>
        public static string Label_StorageRoomArea {
            get {
                return ResourceManager.GetString("Label_StorageRoomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل واحدها در ساختمان.
        /// </summary>
        public static string Label_TotalNumberOfUnits {
            get {
                return ResourceManager.GetString("Label_TotalNumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وام .
        /// </summary>
        public static string Label_TransferableLoanAmount {
            get {
                return ResourceManager.GetString("Label_TransferableLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیربنای واحد.
        /// </summary>
        public static string Label_UnitArea {
            get {
                return ResourceManager.GetString("Label_UnitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه ی واحد.
        /// </summary>
        public static string Label_UnitFloorNumber {
            get {
                return ResourceManager.GetString("Label_UnitFloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری .
        /// </summary>
        public static string Label_UnitUsageType {
            get {
                return ResourceManager.GetString("Label_UnitUsageType", resourceCulture);
            }
        }
    }
}
