//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Controllers.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Controllers.Account.AccountValidationErrors", typeof(AccountValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این حساب کاربری غیر فعال شده است. لطفاً با مدیر سیستم تماس بگیرید..
        /// </summary>
        public static string AccountIsDisabled {
            get {
                return ResourceManager.GetString("AccountIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل تلاش ناموفق متعدد برای ورود، این حساب برای مدتی مسدود شده است. لطفاً بعداً تلاش کنید..
        /// </summary>
        public static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این روش تماس قبلاً اعتبار سنجی شده است..
        /// </summary>
        public static string AlreadyVerified {
            get {
                return ResourceManager.GetString("AlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت ارسال پیامک به این شماره تلفن وجود ندارد.
        /// </summary>
        public static string ContactMethodShouldBeVerifyable {
            get {
                return ResourceManager.GetString("ContactMethodShouldBeVerifyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مستعار مشخص نشده است..
        /// </summary>
        public static string DisplayName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("DisplayName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این روش تماس متعلق به کاربر دیگری است و با موفقیت اعتبار سنجی شده است..
        /// </summary>
        public static string DuplicateContactMethod {
            get {
                return ResourceManager.GetString("DuplicateContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این روش تماس قبلاً برای شما ثبت شده است. برای ثبت مجدد باید ابتدا روش تماس فعلی را حذف کنید..
        /// </summary>
        public static string DuplicateContactMethodForUser {
            get {
                return ResourceManager.GetString("DuplicateContactMethodForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامل مشخص نشده است..
        /// </summary>
        public static string FullName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("FullName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آژانس املاک  باید انتخاب شود.
        /// </summary>
        public static string IndependentAgencyMember_ValueNotSpecified {
            get {
                return ResourceManager.GetString("IndependentAgencyMember_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده صحیح نیست..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن وارد شده، وجود ندارد..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز وارد شده درست نیست..
        /// </summary>
        public static string InvalidSecret {
            get {
                return ResourceManager.GetString("InvalidSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول شناسه کاربر صحیح نیست..
        /// </summary>
        public static string LoginName_ValueDoesNotHaveAppropriateLength {
            get {
                return ResourceManager.GetString("LoginName_ValueDoesNotHaveAppropriateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر مشخص نشده است..
        /// </summary>
        public static string LoginName_ValueNotSpecified {
            get {
                return ResourceManager.GetString("LoginName_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری تکراری است..
        /// </summary>
        public static string LoginNameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("LoginNameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً برای فعال سازی از طریق پست الکترونیک، آدرس ایمیل خود را در این فیلد وارد کنید..
        /// </summary>
        public static string NoEmailAddressProvided {
            get {
                return ResourceManager.GetString("NoEmailAddressProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً برای فعال سازی از طریق پیام کوتاه، شماره تلفن همراه خود را در این فیلد وارد کنید..
        /// </summary>
        public static string NoPhoneNumberProvided {
            get {
                return ResourceManager.GetString("NoPhoneNumberProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده، شماره تلفن صحیحی نیست..
        /// </summary>
        public static string NotAPossiblePhoneNumber {
            get {
                return ResourceManager.GetString("NotAPossiblePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً برای اتمام فعال سازی، رمز ارسال شده را در این قسمت وارد کنید..
        /// </summary>
        public static string NoVerificationSecretProvided {
            get {
                return ResourceManager.GetString("NoVerificationSecretProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط شماره تلفن های همراه برای ارسال پیام کوتاه قابل قبول است..
        /// </summary>
        public static string OnlyMobileNumbersAllowed {
            get {
                return ResourceManager.GetString("OnlyMobileNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعلاً فقط شماره تلفن های داخل کشور ایران برای اعتبار سنجی قابل قبول است..
        /// </summary>
        public static string OnlyNationalNumbersAllowed {
            get {
                return ResourceManager.GetString("OnlyNationalNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کلمه عبور انتخاب شده مناسب نیست..
        /// </summary>
        public static string Password_ValueDoesNotHaveAppropriateLength {
            get {
                return ResourceManager.GetString("Password_ValueDoesNotHaveAppropriateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور مشخص نشده است..
        /// </summary>
        public static string Password_ValueNotSpecified {
            get {
                return ResourceManager.GetString("Password_ValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای امنیت بیشتر، رمز عبور نباید حاوی نام مستعار و یا بخشی از آن باشد..
        /// </summary>
        public static string PasswordCantContainDisplayName {
            get {
                return ResourceManager.GetString("PasswordCantContainDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای امنیت بیشتر، رمز عبور نباید حاوی نام و یا بخشی از آن باشد..
        /// </summary>
        public static string PasswordCantContainFullName {
            get {
                return ResourceManager.GetString("PasswordCantContainFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای امنیت بیشتر، رمز عبور نباید حاوی شناسه کاربری و یا بخشی از آن باشد..
        /// </summary>
        public static string PasswordCantContainLoginName {
            get {
                return ResourceManager.GetString("PasswordCantContainLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر و کلمه عبور وارد شده، صحیح نیستند..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز ارائه شده برای این کاربر نامعتبر است..
        /// </summary>
        public static string PasswordResetTokensDontMatch {
            get {
                return ResourceManager.GetString("PasswordResetTokensDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت اجرای درخواست به پایان رسیده است. لطفاً مجدداً از ابتدا شروع کنید..
        /// </summary>
        public static string RequestHasExpired {
            get {
                return ResourceManager.GetString("RequestHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این روش تماس، اخیراً پیغام فعال سازی ارسال شده است. لطفاً چند دقیقه منتظر بمانید و سپس مجدداً سعی کنید..
        /// </summary>
        public static string TooFrequentContactMethodVerificationStarts {
            get {
                return ResourceManager.GetString("TooFrequentContactMethodVerificationStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این کاربر، اخیراً درخواست دیگری ثبت شده است. لطفاً بعد از چند ساعت مجدداً سعی کنید..
        /// </summary>
        public static string TooFrequentRequests {
            get {
                return ResourceManager.GetString("TooFrequentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش تماس برای اعتبار سنجی پشتیبانی نمی شود..
        /// </summary>
        public static string UnsupportedContactMethodType {
            get {
                return ResourceManager.GetString("UnsupportedContactMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر و کلمه عبور وارد شده، صحیح نیستند..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای نوع فعال سازی این کاربر، این عمل پشتیبانی نمی شود..
        /// </summary>
        public static string UserVerificationMethodNotSupported {
            get {
                return ResourceManager.GetString("UserVerificationMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً آدرس ایمیل مورد استفاده برای فعال سازی را وارد کنید..
        /// </summary>
        public static string Validation_VerificationEmailAddress_Required {
            get {
                return ResourceManager.GetString("Validation_VerificationEmailAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شماره تلفن مورد استفاده برای فعال سازی را وارد کنید..
        /// </summary>
        public static string Validation_VerificationPhoneNumber_Required {
            get {
                return ResourceManager.GetString("Validation_VerificationPhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت استفاده از رمز فعال سازی به اتمام رسیده، لطفا فعال سازی را مجدداً آغاز کنید..
        /// </summary>
        public static string VerificationDeadlineExpired {
            get {
                return ResourceManager.GetString("VerificationDeadlineExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال سازی این حساب آغاز نشده، و رمز فعال سازی وجود ندارد..
        /// </summary>
        public static string VerificationNotStarted {
            get {
                return ResourceManager.GetString("VerificationNotStarted", resourceCulture);
            }
        }
    }
}
