//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BillingPresentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingPresentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Util.Resources.BillingPresentationResources", typeof(BillingPresentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0:#,#.#}.
        /// </summary>
        internal static string NegativeAmountFormat {
            get {
                return ResourceManager.GetString("NegativeAmountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -({0:#,#.#}).
        /// </summary>
        internal static string NegativeBalanceFormat {
            get {
                return ResourceManager.GetString("NegativeBalanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0:#,#.#}.
        /// </summary>
        internal static string NegativeDeltaFormat {
            get {
                return ResourceManager.GetString("NegativeDeltaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,#.#}.
        /// </summary>
        internal static string PositiveAmountFormat {
            get {
                return ResourceManager.GetString("PositiveAmountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,#.#}.
        /// </summary>
        internal static string PositiveBalanceFormat {
            get {
                return ResourceManager.GetString("PositiveBalanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,#.#}.
        /// </summary>
        internal static string PositiveCostFormat {
            get {
                return ResourceManager.GetString("PositiveCostFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0:#,#.#}.
        /// </summary>
        internal static string PositiveDeltaFormat {
            get {
                return ResourceManager.GetString("PositiveDeltaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,#.#}.
        /// </summary>
        internal static string PositiveTurnoverFormat {
            get {
                return ResourceManager.GetString("PositiveTurnoverFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        internal static string ZeroAmount {
            get {
                return ResourceManager.GetString("ZeroAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        internal static string ZeroBalance {
            get {
                return ResourceManager.GetString("ZeroBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون هزینه.
        /// </summary>
        internal static string ZeroCost {
            get {
                return ResourceManager.GetString("ZeroCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون تغییر.
        /// </summary>
        internal static string ZeroDelta {
            get {
                return ResourceManager.GetString("ZeroDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        internal static string ZeroTurnover {
            get {
                return ResourceManager.GetString("ZeroTurnover", resourceCulture);
            }
        }
    }
}
