//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainBillingEnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainBillingEnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Util.Resources.DomainBillingEnumResources", typeof(DomainBillingEnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک دی.
        /// </summary>
        public static string IranianBank_Dey {
            get {
                return ResourceManager.GetString("IranianBank_Dey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک اقتصاد نوین.
        /// </summary>
        public static string IranianBank_EghtesadNovin {
            get {
                return ResourceManager.GetString("IranianBank_EghtesadNovin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک کشاورزی.
        /// </summary>
        public static string IranianBank_Keshavarzi {
            get {
                return ResourceManager.GetString("IranianBank_Keshavarzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک مسکن.
        /// </summary>
        public static string IranianBank_Maskan {
            get {
                return ResourceManager.GetString("IranianBank_Maskan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک ملت.
        /// </summary>
        public static string IranianBank_Mellat {
            get {
                return ResourceManager.GetString("IranianBank_Mellat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک ملی.
        /// </summary>
        public static string IranianBank_Melli {
            get {
                return ResourceManager.GetString("IranianBank_Melli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر بانک ها.
        /// </summary>
        public static string IranianBank_Other {
            get {
                return ResourceManager.GetString("IranianBank_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک پارسیان.
        /// </summary>
        public static string IranianBank_Parsian {
            get {
                return ResourceManager.GetString("IranianBank_Parsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک پاسارگاد.
        /// </summary>
        public static string IranianBank_Pasargad {
            get {
                return ResourceManager.GetString("IranianBank_Pasargad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک رفاه.
        /// </summary>
        public static string IranianBank_Refah {
            get {
                return ResourceManager.GetString("IranianBank_Refah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک صادرات.
        /// </summary>
        public static string IranianBank_Saderat {
            get {
                return ResourceManager.GetString("IranianBank_Saderat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک سامان.
        /// </summary>
        public static string IranianBank_Saman {
            get {
                return ResourceManager.GetString("IranianBank_Saman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک سرمایه.
        /// </summary>
        public static string IranianBank_Sarmayeh {
            get {
                return ResourceManager.GetString("IranianBank_Sarmayeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک سپه.
        /// </summary>
        public static string IranianBank_Sepah {
            get {
                return ResourceManager.GetString("IranianBank_Sepah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک شهر.
        /// </summary>
        public static string IranianBank_Shahr {
            get {
                return ResourceManager.GetString("IranianBank_Shahr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک سینا.
        /// </summary>
        public static string IranianBank_Sina {
            get {
                return ResourceManager.GetString("IranianBank_Sina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک تجارت.
        /// </summary>
        public static string IranianBank_Tejarat {
            get {
                return ResourceManager.GetString("IranianBank_Tejarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک پاسارگاد.
        /// </summary>
        public static string PaymentGatewayProvider_Pasargad {
            get {
                return ResourceManager.GetString("PaymentGatewayProvider_Pasargad", resourceCulture);
            }
        }
    }
}
