//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Util.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- همه موارد --.
        /// </summary>
        public static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشناس.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ، .
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متر.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میلیون تومان.
        /// </summary>
        public static string MillionTomans {
            get {
                return ResourceManager.GetString("MillionTomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام نشده.
        /// </summary>
        public static string NotPerformed {
            get {
                return ResourceManager.GetString("NotPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- انتخاب نشده --.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string Paranthesis {
            get {
                return ResourceManager.GetString("Paranthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً چند لحظه صبر کنید....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ؟.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string Rials {
            get {
                return ResourceManager.GetString("Rials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- لطفاً انتخاب کنید --.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ؛ .
        /// </summary>
        public static string Semicolon {
            get {
                return ResourceManager.GetString("Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متر مربع.
        /// </summary>
        public static string SquareMeter {
            get {
                return ResourceManager.GetString("SquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزار تومان.
        /// </summary>
        public static string ThousandTomans {
            get {
                return ResourceManager.GetString("ThousandTomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بار.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} بار.
        /// </summary>
        public static string TimesFormat {
            get {
                return ResourceManager.GetString("TimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        public static string Tomans {
            get {
                return ResourceManager.GetString("Tomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
