//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Core.Impl.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailNotificationServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailNotificationServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Core.Impl.Services.Resources.EmailNotificationServiceResourc" +
                            "es", typeof(EmailNotificationServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار مالی شما به پایان رسیده است.
        /// </summary>
        internal static string BalanceDepleted_Subject {
            get {
                return ResourceManager.GetString("BalanceDepleted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار مالی شما رو به پایان است.
        /// </summary>
        internal static string BalanceRunningLow_Subject {
            get {
                return ResourceManager.GetString("BalanceRunningLow_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار رایگان به شما تعلق گرفت.
        /// </summary>
        internal static string BonusInformation_Subject {
            get {
                return ResourceManager.GetString("BonusInformation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدتیه که شما رو ندیدیم.
        /// </summary>
        internal static string InactiveUser_Subject {
            get {
                return ResourceManager.GetString("InactiveUser_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نام کاربری.
        /// </summary>
        internal static string LoginNameQuery_Subject {
            get {
                return ResourceManager.GetString("LoginNameQuery_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب شما غیر فعال شده است.
        /// </summary>
        internal static string NotifyAccountHasBeenDisabled_Subject {
            get {
                return ResourceManager.GetString("NotifyAccountHasBeenDisabled_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از آدرس شما برای بازیابی کلمه عبور.
        /// </summary>
        internal static string NotifyNonRegisteredEmailUsedForPasswordRecovery_Subject {
            get {
                return ResourceManager.GetString("NotifyNonRegisteredEmailUsedForPasswordRecovery_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از آدرس شما برای بازیابی کلمه عبور.
        /// </summary>
        internal static string NotifyNonVerifiedEmailUsedForPasswordRecovery_Subject {
            get {
                return ResourceManager.GetString("NotifyNonVerifiedEmailUsedForPasswordRecovery_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع بازیابی کلمه عبور با استفاده از پیام کوتاه.
        /// </summary>
        internal static string NotifyPasswordRecoveryBySmsStarted_Subject {
            get {
                return ResourceManager.GetString("NotifyPasswordRecoveryBySmsStarted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل بازیابی کلمه عبور.
        /// </summary>
        internal static string NotifyPasswordRecoveryComplete_Subject {
            get {
                return ResourceManager.GetString("NotifyPasswordRecoveryComplete_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آگهی ملک شما در حال پایان یافتن است.
        /// </summary>
        internal static string NotifyPublishAboutToExpire_Subject {
            get {
                return ResourceManager.GetString("NotifyPublishAboutToExpire_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کارت به کارت شده ، در حساب شما منظور شد .
        /// </summary>
        internal static string NotifyWireTransferPayment_Subject {
            get {
                return ResourceManager.GetString("NotifyWireTransferPayment_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تنظیم مجدد کلمه عبور.
        /// </summary>
        internal static string PasswordReset_Subject {
            get {
                return ResourceManager.GetString("PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات ملک نتیجه جستجو: {0}.
        /// </summary>
        internal static string PropertyInfoForSavedSearch_Subject {
            get {
                return ResourceManager.GetString("PropertyInfoForSavedSearch_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ملک ثبت شده.
        /// </summary>
        internal static string SendPropertyRegistrationInfoToOwner_Subject {
            get {
                return ResourceManager.GetString("SendPropertyRegistrationInfoToOwner_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال سازی آدرس ایمیل.
        /// </summary>
        internal static string SendVerification_Subject {
            get {
                return ResourceManager.GetString("SendVerification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ملک رو تو خونه ت ببین.
        /// </summary>
        internal static string SharePropertyListing_Subject {
            get {
                return ResourceManager.GetString("SharePropertyListing_Subject", resourceCulture);
            }
        }
    }
}
