//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Areas.Billing.Models.Refund {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RefundModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefundModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Areas.Billing.Models.Refund.RefundModelResources", typeof(RefundModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل مبلغ.
        /// </summary>
        public static string CheckBox_RequestedMaximumAmount {
            get {
                return ResourceManager.GetString("CheckBox_RequestedMaximumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواست شده.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صاحب حساب.
        /// </summary>
        public static string Label_TargetAccountHolderName {
            get {
                return ResourceManager.GetString("Label_TargetAccountHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک مقصد .
        /// </summary>
        public static string Label_TargetBank {
            get {
                return ResourceManager.GetString("Label_TargetBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت مقصد.
        /// </summary>
        public static string Label_TargetCardNumber {
            get {
                return ResourceManager.GetString("Label_TargetCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string Label_TargetShebaNumber {
            get {
                return ResourceManager.GetString("Label_TargetShebaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Label_UserEnteredDescription {
            get {
                return ResourceManager.GetString("Label_UserEnteredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً دلیل درخواست خود را مطرح کنید.
        /// </summary>
        public static string Label_UserEnteredReason {
            get {
                return ResourceManager.GetString("Label_UserEnteredReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل مانده حساب.
        /// </summary>
        public static string MaximumAmount {
            get {
                return ResourceManager.GetString("MaximumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت یا شماره شبا را وارد نمایید.
        /// </summary>
        public static string Validation_Account_Info {
            get {
                return ResourceManager.GetString("Validation_Account_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یک مقدار عددی وارد کنید.
        /// </summary>
        public static string Validation_Amount_Numeric {
            get {
                return ResourceManager.GetString("Validation_Amount_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_Amount_Range {
            get {
                return ResourceManager.GetString("Validation_Amount_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مبلغ واریز شده را مشخص نمایید.
        /// </summary>
        public static string Validation_Amount_Required {
            get {
                return ResourceManager.GetString("Validation_Amount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_TargetAccountHolderName_Length {
            get {
                return ResourceManager.GetString("Validation_TargetAccountHolderName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام صاحب حساب را مشخص کنید.
        /// </summary>
        public static string Validation_TargetAccountHolderName_Required {
            get {
                return ResourceManager.GetString("Validation_TargetAccountHolderName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً بانک مقصد را مشخص کنید.
        /// </summary>
        public static string Validation_TargetBank_Required {
            get {
                return ResourceManager.GetString("Validation_TargetBank_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_TargetCardNumber_Length {
            get {
                return ResourceManager.GetString("Validation_TargetCardNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_TargetShebaNumber_Length {
            get {
                return ResourceManager.GetString("Validation_TargetShebaNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_UserEnteredDescription_Length {
            get {
                return ResourceManager.GetString("Validation_UserEnteredDescription_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول مقدار وارد شده خارج از محدوده مجاز است.
        /// </summary>
        public static string Validation_UserEnteredReason_Length {
            get {
                return ResourceManager.GetString("Validation_UserEnteredReason_Length", resourceCulture);
            }
        }
    }
}
