//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Views.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesBrowseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesBrowseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Views.Properties.PropertiesBrowseResources", typeof(PropertiesBrowseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه املاک.
        /// </summary>
        public static string AllProperties {
            get {
                return ResourceManager.GetString("AllProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپارتمان.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزان ترین.
        /// </summary>
        public static string CheapestFirst {
            get {
                return ResourceManager.GetString("CheapestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در شهر: {0}.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در منطقه شهرداری: {0}.
        /// </summary>
        public static string CityRegion {
            get {
                return ResourceManager.GetString("CityRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن و اجاره.
        /// </summary>
        public static string ForRent {
            get {
                return ResourceManager.GetString("ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید / فروش.
        /// </summary>
        public static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باغ.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه دربست.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قرارداد: {0}.
        /// </summary>
        public static string IntentionOfOwner {
            get {
                return ResourceManager.GetString("IntentionOfOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین.
        /// </summary>
        public static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگ ترین.
        /// </summary>
        public static string LargestFirst {
            get {
                return ResourceManager.GetString("LargestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گران ترین.
        /// </summary>
        public static string MoreExpensiveFirst {
            get {
                return ResourceManager.GetString("MoreExpensiveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پربیننده ترین.
        /// </summary>
        public static string MostPopularFirst {
            get {
                return ResourceManager.GetString("MostPopularFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در محله: {0}.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در {0} محله ا نتخاب شده.
        /// </summary>
        public static string Neighborhoods {
            get {
                return ResourceManager.GetString("Neighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید ترین.
        /// </summary>
        public static string NewestFirst {
            get {
                return ResourceManager.GetString("NewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل کار توسط بنگاه املاک.
        /// </summary>
        public static string option_agencyactivityallowed {
            get {
                return ResourceManager.GetString("option_agencyactivityallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختمان حداکثر 10 واحدی.
        /// </summary>
        public static string option_buildinghaslessthan10units {
            get {
                return ResourceManager.GetString("option_buildinghaslessthan10units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختمان حداکثر 5 واحدی.
        /// </summary>
        public static string option_buildinghaslessthan5units {
            get {
                return ResourceManager.GetString("option_buildinghaslessthan5units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختمان حداقل 10 واحدی.
        /// </summary>
        public static string option_buildinghasmorethan10units {
            get {
                return ResourceManager.GetString("option_buildinghasmorethan10units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین دو کله.
        /// </summary>
        public static string option_estatedirectionisboth {
            get {
                return ResourceManager.GetString("option_estatedirectionisboth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین شمالی.
        /// </summary>
        public static string option_estatedirectionisnorth {
            get {
                return ResourceManager.GetString("option_estatedirectionisnorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین جنوبی.
        /// </summary>
        public static string option_estatedirectionissouth {
            get {
                return ResourceManager.GetString("option_estatedirectionissouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین کم شیب.
        /// </summary>
        public static string option_estatehaslowslope {
            get {
                return ResourceManager.GetString("option_estatehaslowslope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین حداقل 3 بر.
        /// </summary>
        public static string option_estatehasthreesidesminimum {
            get {
                return ResourceManager.GetString("option_estatehasthreesidesminimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین حداقل 2 بر.
        /// </summary>
        public static string option_estatehastwosidesminimum {
            get {
                return ResourceManager.GetString("option_estatehastwosidesminimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین دارای سند منگوله دار.
        /// </summary>
        public static string option_estatevouchertypeisnormal {
            get {
                return ResourceManager.GetString("option_estatevouchertypeisnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل استفاده توسط معلولین.
        /// </summary>
        public static string option_hasaccessibilityfeatures {
            get {
                return ResourceManager.GetString("option_hasaccessibilityfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای درب ریموتی.
        /// </summary>
        public static string option_hasautomaticparkingdoor {
            get {
                return ResourceManager.GetString("option_hasautomaticparkingdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازسازی شده.
        /// </summary>
        public static string option_hasbeenreconstructed {
            get {
                return ResourceManager.GetString("option_hasbeenreconstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای کارواش.
        /// </summary>
        public static string option_hascarwash {
            get {
                return ResourceManager.GetString("option_hascarwash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای سیستم حرارت مرکزی.
        /// </summary>
        public static string option_hascentralboiler {
            get {
                return ResourceManager.GetString("option_hascentralboiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای سیستم چیلر مرکزی.
        /// </summary>
        public static string option_hascentralchiller {
            get {
                return ResourceManager.GetString("option_hascentralchiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای ارتباط اینترنت.
        /// </summary>
        public static string option_hascentralinternetconnection {
            get {
                return ResourceManager.GetString("option_hascentralinternetconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آنتن مرکزی تلویزیون.
        /// </summary>
        public static string option_hascentraltelevisionantenna {
            get {
                return ResourceManager.GetString("option_hascentraltelevisionantenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای جاروبرقی مرکزی.
        /// </summary>
        public static string option_hascentralvacuum {
            get {
                return ResourceManager.GetString("option_hascentralvacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای نمای پانل کامپوزیت.
        /// </summary>
        public static string option_hascompositepanelface {
            get {
                return ResourceManager.GetString("option_hascompositepanelface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پنجره دوجداره.
        /// </summary>
        public static string option_hasduallayerwindows {
            get {
                return ResourceManager.GetString("option_hasduallayerwindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آسانسور.
        /// </summary>
        public static string option_haselevator {
            get {
                return ResourceManager.GetString("option_haselevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای لابی ورودی.
        /// </summary>
        public static string option_hasentrancelobby {
            get {
                return ResourceManager.GetString("option_hasentrancelobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای شومینه.
        /// </summary>
        public static string option_hasfireplace {
            get {
                return ResourceManager.GetString("option_hasfireplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای توالت فرنگی.
        /// </summary>
        public static string option_hasforeignlavatory {
            get {
                return ResourceManager.GetString("option_hasforeignlavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آسانسور بار.
        /// </summary>
        public static string option_hasfurnitureelevator {
            get {
                return ResourceManager.GetString("option_hasfurnitureelevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای سالن اجتماعات.
        /// </summary>
        public static string option_hasgatheringhall {
            get {
                return ResourceManager.GetString("option_hasgatheringhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای باغچه سرسبز.
        /// </summary>
        public static string option_hasgreengarden {
            get {
                return ResourceManager.GetString("option_hasgreengarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای نگهبان.
        /// </summary>
        public static string option_hasguardian {
            get {
                return ResourceManager.GetString("option_hasguardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پارکینگ مهمان.
        /// </summary>
        public static string option_hasguestparking {
            get {
                return ResourceManager.GetString("option_hasguestparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای سالن با امکانات ورزشی.
        /// </summary>
        public static string option_hasgym {
            get {
                return ResourceManager.GetString("option_hasgym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پکیج مستقل سرمایش.
        /// </summary>
        public static string option_hasindependentcoolingpackage {
            get {
                return ResourceManager.GetString("option_hasindependentcoolingpackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پکیج مستقل گرمایش.
        /// </summary>
        public static string option_hasindependentheatingpackage {
            get {
                return ResourceManager.GetString("option_hasindependentheatingpackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای توالت ایرانی.
        /// </summary>
        public static string option_hasiranianlavatory {
            get {
                return ResourceManager.GetString("option_hasiranianlavatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای جکوزی.
        /// </summary>
        public static string option_hasjacuzzi {
            get {
                return ResourceManager.GetString("option_hasjacuzzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای واحد سرایداری.
        /// </summary>
        public static string option_hasjanitorunit {
            get {
                return ResourceManager.GetString("option_hasjanitorunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آشپزخانه ام دی اف.
        /// </summary>
        public static string option_hasmdftypekitchen {
            get {
                return ResourceManager.GetString("option_hasmdftypekitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آشپزخانه باز (اپن).
        /// </summary>
        public static string option_hasopenkitchen {
            get {
                return ResourceManager.GetString("option_hasopenkitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پارکینگ.
        /// </summary>
        public static string option_hasparking {
            get {
                return ResourceManager.GetString("option_hasparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط املاک دارای عکس.
        /// </summary>
        public static string option_hasphotos {
            get {
                return ResourceManager.GetString("option_hasphotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پاسیوی خصوصی.
        /// </summary>
        public static string option_hasprivatepatio {
            get {
                return ResourceManager.GetString("option_hasprivatepatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای سونا.
        /// </summary>
        public static string option_hassauna {
            get {
                return ResourceManager.GetString("option_hassauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای نور جنوب.
        /// </summary>
        public static string option_hassouthdaylight {
            get {
                return ResourceManager.GetString("option_hassouthdaylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای نمای سنگی.
        /// </summary>
        public static string option_hasstoneface {
            get {
                return ResourceManager.GetString("option_hasstoneface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای انباری.
        /// </summary>
        public static string option_hasstorageroom {
            get {
                return ResourceManager.GetString("option_hasstorageroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای استخر.
        /// </summary>
        public static string option_hasswimmingpool {
            get {
                return ResourceManager.GetString("option_hasswimmingpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای پنجره های یو پی وی سی.
        /// </summary>
        public static string option_hasupvcwindows {
            get {
                return ResourceManager.GetString("option_hasupvcwindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای آیفون تصویری.
        /// </summary>
        public static string option_hasvideoeyephone {
            get {
                return ResourceManager.GetString("option_hasvideoeyephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای چاه آب.
        /// </summary>
        public static string option_haswaterwells {
            get {
                return ResourceManager.GetString("option_haswaterwells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در نزدیکی پارک واقع شده است.
        /// </summary>
        public static string option_isclosetopark {
            get {
                return ResourceManager.GetString("option_isclosetopark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوبلکس است.
        /// </summary>
        public static string option_isduplex {
            get {
                return ResourceManager.GetString("option_isduplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید نخورده یا تخلیه.
        /// </summary>
        public static string option_isempty {
            get {
                return ResourceManager.GetString("option_isempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در بن بست واقع شده.
        /// </summary>
        public static string option_isindeadend {
            get {
                return ResourceManager.GetString("option_isindeadend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نزدیک بزرگ راه نیست.
        /// </summary>
        public static string option_isnotclosetohighway {
            get {
                return ResourceManager.GetString("option_isnotclosetohighway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ساخت نیست.
        /// </summary>
        public static string option_isnotinconstruction {
            get {
                return ResourceManager.GetString("option_isnotinconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در بن بست واقع نشده است.
        /// </summary>
        public static string option_isnotindeadend {
            get {
                return ResourceManager.GetString("option_isnotindeadend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در گذر اصلی واقع نشده است.
        /// </summary>
        public static string option_isnotonmainpassage {
            get {
                return ResourceManager.GetString("option_isnotonmainpassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در گذر مشجر واقع شده است.
        /// </summary>
        public static string option_isongreenpassage {
            get {
                return ResourceManager.GetString("option_isongreenpassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در طبقه همکف یا اول واقع شده.
        /// </summary>
        public static string option_isongroundfloor {
            get {
                return ResourceManager.GetString("option_isongroundfloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگذر اصلی واقع شده است.
        /// </summary>
        public static string option_isonmainpassage {
            get {
                return ResourceManager.GetString("option_isonmainpassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای کاربری مسکونی.
        /// </summary>
        public static string option_isresidential {
            get {
                return ResourceManager.GetString("option_isresidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای طبقات تک واحدی.
        /// </summary>
        public static string option_issingleunitperfloor {
            get {
                return ResourceManager.GetString("option_issingleunitperfloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط آگهی بی واسطه.
        /// </summary>
        public static string option_noagencylisting {
            get {
                return ResourceManager.GetString("option_noagencylisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای اسکلت بتونی است.
        /// </summary>
        public static string option_structureisconcrete {
            get {
                return ResourceManager.GetString("option_structureisconcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارای اسکلت فلزی است.
        /// </summary>
        public static string option_structureisironbeam {
            get {
                return ResourceManager.GetString("option_structureisironbeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط املاک برگزیده توسط من.
        /// </summary>
        public static string option_userhasstarred {
            get {
                return ResourceManager.GetString("option_userhasstarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط املاک ثبت شده توسط من.
        /// </summary>
        public static string option_userisowner {
            get {
                return ResourceManager.GetString("option_userisowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر شرایط.
        /// </summary>
        public static string OtherFilters {
            get {
                return ResourceManager.GetString("OtherFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنت هاوس.
        /// </summary>
        public static string Penthouse {
            get {
                return ResourceManager.GetString("Penthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر مساحت زمین: {0} متر.
        /// </summary>
        public static string property_EstateAreaMaximum {
            get {
                return ResourceManager.GetString("property_EstateAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مساحت زمین: {0} متر.
        /// </summary>
        public static string property_EstateAreaMinimum {
            get {
                return ResourceManager.GetString("property_EstateAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد پارکینگ: {0}.
        /// </summary>
        public static string property_NumberOfParkingsMinimum {
            get {
                return ResourceManager.GetString("property_NumberOfParkingsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد اتاق: {0}.
        /// </summary>
        public static string property_NumberOfRoomsMaximum {
            get {
                return ResourceManager.GetString("property_NumberOfRoomsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد اتاق: {0}.
        /// </summary>
        public static string property_NumberOfRoomsMinimum {
            get {
                return ResourceManager.GetString("property_NumberOfRoomsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر اجاره: {0:#,###} تومان.
        /// </summary>
        public static string property_RentMaximum {
            get {
                return ResourceManager.GetString("property_RentMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل اجاره: {0:#,###} تومان.
        /// </summary>
        public static string property_RentMinimum {
            get {
                return ResourceManager.GetString("property_RentMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر رهن: {0:#,###} تومان.
        /// </summary>
        public static string property_RentMortgageMaximum {
            get {
                return ResourceManager.GetString("property_RentMortgageMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل رهن: {0:#,###} تومان.
        /// </summary>
        public static string property_RentMortgageMinimum {
            get {
                return ResourceManager.GetString("property_RentMortgageMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل &lt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePriceMaximum {
            get {
                return ResourceManager.GetString("property_SalePriceMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل &gt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePriceMinimum {
            get {
                return ResourceManager.GetString("property_SalePriceMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین متری &lt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePricePerEstateAreaMaximum {
            get {
                return ResourceManager.GetString("property_SalePricePerEstateAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین متری &gt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePricePerEstateAreaMinimum {
            get {
                return ResourceManager.GetString("property_SalePricePerEstateAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنا متری &lt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePricePerUnitAreaMaximum {
            get {
                return ResourceManager.GetString("property_SalePricePerUnitAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنا متری &gt; {0:#,###} ت.
        /// </summary>
        public static string property_SalePricePerUnitAreaMinimum {
            get {
                return ResourceManager.GetString("property_SalePricePerUnitAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر مساحت واحد: {0} متر.
        /// </summary>
        public static string property_UnitAreaMaximum {
            get {
                return ResourceManager.GetString("property_UnitAreaMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مساحت واحد: {0} متر.
        /// </summary>
        public static string property_UnitAreaMinimum {
            get {
                return ResourceManager.GetString("property_UnitAreaMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملک: {0}.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در استان: {0}.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغازه.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچک ترین.
        /// </summary>
        public static string SmallestFirst {
            get {
                return ResourceManager.GetString("SmallestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت : {0}.
        /// </summary>
        public static string Vicinities {
            get {
                return ResourceManager.GetString("Vicinities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت : {0}.
        /// </summary>
        public static string Vicinity {
            get {
                return ResourceManager.GetString("Vicinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویلا / خانه ویلایی.
        /// </summary>
        public static string Villa {
            get {
                return ResourceManager.GetString("Villa", resourceCulture);
            }
        }
    }
}
