//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Resources.Helpers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertySearchTitleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertySearchTitleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Resources.Helpers.Properties.PropertySearchTitleResource" +
                            "s", typeof(PropertySearchTitleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه املاک.
        /// </summary>
        public static string AllProperties {
            get {
                return ResourceManager.GetString("AllProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر {0}.
        /// </summary>
        public static string CityTitleFormat {
            get {
                return ResourceManager.GetString("CityTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IntentionOfOwner_All {
            get {
                return ResourceManager.GetString("IntentionOfOwner_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن و اجاره.
        /// </summary>
        public static string IntentionOfOwner_ForRent {
            get {
                return ResourceManager.GetString("IntentionOfOwner_ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید و فروش.
        /// </summary>
        public static string IntentionOfOwner_ForSale {
            get {
                return ResourceManager.GetString("IntentionOfOwner_ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در {0}.
        /// </summary>
        public static string LocationTitleFormat {
            get {
                return ResourceManager.GetString("LocationTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله های {0} در شهر {1}.
        /// </summary>
        public static string MultipleNeighborhoodNamesInCity {
            get {
                return ResourceManager.GetString("MultipleNeighborhoodNamesInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله های {0} در {1} شهر {2}.
        /// </summary>
        public static string MultipleNeighborhoodNamesInCityAndCityRegion {
            get {
                return ResourceManager.GetString("MultipleNeighborhoodNamesInCityAndCityRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله های {0} در {1}.
        /// </summary>
        public static string MultipleNeighborhoodNamesInCityRegion {
            get {
                return ResourceManager.GetString("MultipleNeighborhoodNamesInCityRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} محله.
        /// </summary>
        public static string MultipleNeighborhoods {
            get {
                return ResourceManager.GetString("MultipleNeighborhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در {0} محله.
        /// </summary>
        public static string MultipleVicinityNames {
            get {
                return ResourceManager.GetString("MultipleVicinityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه انواع املاک.
        /// </summary>
        public static string PropertyType_All {
            get {
                return ResourceManager.GetString("PropertyType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپارتمان.
        /// </summary>
        public static string PropertyType_Apartment {
            get {
                return ResourceManager.GetString("PropertyType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باغ یا باغچه.
        /// </summary>
        public static string PropertyType_Garden {
            get {
                return ResourceManager.GetString("PropertyType_Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه مستقل.
        /// </summary>
        public static string PropertyType_House {
            get {
                return ResourceManager.GetString("PropertyType_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین.
        /// </summary>
        public static string PropertyType_Land {
            get {
                return ResourceManager.GetString("PropertyType_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنت هاوس.
        /// </summary>
        public static string PropertyType_Penthouse {
            get {
                return ResourceManager.GetString("PropertyType_Penthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویلا.
        /// </summary>
        public static string PropertyType_Villa {
            get {
                return ResourceManager.GetString("PropertyType_Villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان {0}.
        /// </summary>
        public static string ProvinceTitleFormat {
            get {
                return ResourceManager.GetString("ProvinceTitleFormat", resourceCulture);
            }
        }
    }
}
