//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanJooy.RealEstate.Web.Areas.Admin.Resources.AdminActivityLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityLogEntityTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityLogEntityTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanJooy.RealEstate.Web.Areas.Admin.Resources.AdminActivityLog.ActivityLogEntity" +
                            "TypeResources", typeof(ActivityLogEntityTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی نام کاربری.
        /// </summary>
        public static string AuditEntity_LoginNameQuery {
            get {
                return ResourceManager.GetString("AuditEntity_LoginNameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string AuditEntity_PasswordResetRequest {
            get {
                return ResourceManager.GetString("AuditEntity_PasswordResetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه انتشار ملک.
        /// </summary>
        public static string AuditEntity_PropertyListingPublishHistory {
            get {
                return ResourceManager.GetString("AuditEntity_PropertyListingPublishHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه تغییرات ملک.
        /// </summary>
        public static string AuditEntity_PropertyListingUpdateHistory {
            get {
                return ResourceManager.GetString("AuditEntity_PropertyListingUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال سازی روش تماس.
        /// </summary>
        public static string AuditEntity_UserContactMethodVerification {
            get {
                return ResourceManager.GetString("AuditEntity_UserContactMethodVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش مالی کاربر.
        /// </summary>
        public static string DetailEntity_UserBillingTransaction {
            get {
                return ResourceManager.GetString("DetailEntity_UserBillingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش تماس کاربر.
        /// </summary>
        public static string DetailEntity_UserContactMethod {
            get {
                return ResourceManager.GetString("DetailEntity_UserContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش سوء استفاده.
        /// </summary>
        public static string TargetEntity_AbuseFlag {
            get {
                return ResourceManager.GetString("TargetEntity_AbuseFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string TargetEntity_City {
            get {
                return ResourceManager.GetString("TargetEntity_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه شهر.
        /// </summary>
        public static string TargetEntity_CityRegion {
            get {
                return ResourceManager.GetString("TargetEntity_CityRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیکربندی.
        /// </summary>
        public static string TargetEntity_ConfigurationDataItem {
            get {
                return ResourceManager.GetString("TargetEntity_ConfigurationDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محله شهر.
        /// </summary>
        public static string TargetEntity_Neighborhood {
            get {
                return ResourceManager.GetString("TargetEntity_Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جایزه.
        /// </summary>
        public static string TargetEntity_PromotionalBonus {
            get {
                return ResourceManager.GetString("TargetEntity_PromotionalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت جایزه.
        /// </summary>
        public static string TargetEntity_PromotionalBonusCoupon {
            get {
                return ResourceManager.GetString("TargetEntity_PromotionalBonusCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک.
        /// </summary>
        public static string TargetEntity_PropertyListing {
            get {
                return ResourceManager.GetString("TargetEntity_PropertyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس ملک.
        /// </summary>
        public static string TargetEntity_PropertyListingPhoto {
            get {
                return ResourceManager.GetString("TargetEntity_PropertyListingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string TargetEntity_Province {
            get {
                return ResourceManager.GetString("TargetEntity_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی ذخیره شده.
        /// </summary>
        public static string TargetEntity_SavedPropertySearch {
            get {
                return ResourceManager.GetString("TargetEntity_SavedPropertySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string TargetEntity_User {
            get {
                return ResourceManager.GetString("TargetEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر مانده حساب.
        /// </summary>
        public static string TargetEntity_UserBalanceAdministrativeChange {
            get {
                return ResourceManager.GetString("TargetEntity_UserBalanceAdministrativeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت الکترونیکی.
        /// </summary>
        public static string TargetEntity_UserElectronicPayment {
            get {
                return ResourceManager.GetString("TargetEntity_UserElectronicPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازپرداخت.
        /// </summary>
        public static string TargetEntity_UserRefundRequest {
            get {
                return ResourceManager.GetString("TargetEntity_UserRefundRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت کارت به کارت.
        /// </summary>
        public static string TargetEntity_UserWireTransferPayment {
            get {
                return ResourceManager.GetString("TargetEntity_UserWireTransferPayment", resourceCulture);
            }
        }
    }
}
